// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.spruceid.sprucekit_mobile

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MdlPresentationPigeonUtils {

  fun createConnectionError(channelName: String): MdlPresentationFlutterError {
    return MdlPresentationFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is MdlPresentationFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class MdlPresentationFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Presentation state for ISO 18013-5 mDL presentation */
enum class MdlPresentationState(val raw: Int) {
  /** Initial state, not yet started */
  UNINITIALIZED(0),
  /** Waiting for Bluetooth/transport to be ready */
  INITIALIZING(1),
  /** Bluetooth needs to be turned on to continue */
  BLUETOOTH_REQUIRED(2),
  /** Bluetooth authorization required in Settings */
  BLUETOOTH_AUTHORIZATION_REQUIRED(3),
  /** QR code is ready to be displayed */
  ENGAGING_QR_CODE(4),
  /** Reader has connected, waiting for request */
  CONNECTED(5),
  /** Received request from reader, user needs to select fields */
  SELECTING_NAMESPACES(6),
  /** Sending response to reader */
  SENDING_RESPONSE(7),
  /** Successfully sent response */
  SUCCESS(8),
  /** Session timed out */
  TIMEOUT(9),
  /** Reader disconnected unexpectedly */
  READER_DISCONNECTED(10),
  /** An error occurred */
  ERROR(11);

  companion object {
    fun ofRaw(raw: Int): MdlPresentationState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Requested item from a namespace
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MdlNamespaceItem (
  /** Field name */
  val name: String,
  /** Whether the field is required by the reader */
  val intentToRetain: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MdlNamespaceItem {
      val name = pigeonVar_list[0] as String
      val intentToRetain = pigeonVar_list[1] as Boolean
      return MdlNamespaceItem(name, intentToRetain)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      intentToRetain,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MdlNamespaceItem) {
      return false
    }
    if (this === other) {
      return true
    }
    return MdlPresentationPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Request from reader for a specific namespace
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MdlNamespaceRequest (
  /** Namespace identifier (e.g., "org.iso.18013.5.1") */
  val namespace: String,
  /** Items requested in this namespace */
  val items: List<MdlNamespaceItem>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MdlNamespaceRequest {
      val namespace = pigeonVar_list[0] as String
      val items = pigeonVar_list[1] as List<MdlNamespaceItem>
      return MdlNamespaceRequest(namespace, items)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      namespace,
      items,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MdlNamespaceRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MdlPresentationPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Items request from reader for a specific docType
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MdlItemsRequest (
  /** Document type (e.g., "org.iso.18013.5.1.mDL") */
  val docType: String,
  /** Namespaces and their requested items */
  val namespaces: List<MdlNamespaceRequest>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MdlItemsRequest {
      val docType = pigeonVar_list[0] as String
      val namespaces = pigeonVar_list[1] as List<MdlNamespaceRequest>
      return MdlItemsRequest(docType, namespaces)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      docType,
      namespaces,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MdlItemsRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MdlPresentationPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * State update event from the presentation session
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MdlPresentationStateUpdate (
  /** Current state */
  val state: MdlPresentationState,
  /** QR code URI (only set when state is engagingQrCode) */
  val qrCodeUri: String? = null,
  /** Items requests from reader (only set when state is selectingNamespaces) */
  val itemsRequests: List<MdlItemsRequest>? = null,
  /** Error message (only set when state is error) */
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MdlPresentationStateUpdate {
      val state = pigeonVar_list[0] as MdlPresentationState
      val qrCodeUri = pigeonVar_list[1] as String?
      val itemsRequests = pigeonVar_list[2] as List<MdlItemsRequest>?
      val error = pigeonVar_list[3] as String?
      return MdlPresentationStateUpdate(state, qrCodeUri, itemsRequests, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      qrCodeUri,
      itemsRequests,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MdlPresentationStateUpdate) {
      return false
    }
    if (this === other) {
      return true
    }
    return MdlPresentationPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result type for presentation operations
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class MdlPresentationResult 
/**
 * Operation succeeded
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MdlPresentationSuccess (
  val message: String? = null
) : MdlPresentationResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MdlPresentationSuccess {
      val message = pigeonVar_list[0] as String?
      return MdlPresentationSuccess(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MdlPresentationSuccess) {
      return false
    }
    if (this === other) {
      return true
    }
    return MdlPresentationPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Operation failed
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MdlPresentationError (
  val message: String
) : MdlPresentationResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MdlPresentationError {
      val message = pigeonVar_list[0] as String
      return MdlPresentationError(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MdlPresentationError) {
      return false
    }
    if (this === other) {
      return true
    }
    return MdlPresentationPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MdlPresentationPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MdlPresentationState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MdlNamespaceItem.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MdlNamespaceRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MdlItemsRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MdlPresentationStateUpdate.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MdlPresentationSuccess.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MdlPresentationError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MdlPresentationState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is MdlNamespaceItem -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is MdlNamespaceRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MdlItemsRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MdlPresentationStateUpdate -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MdlPresentationSuccess -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is MdlPresentationError -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Callback interface for presentation state updates
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class MdlPresentationCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MdlPresentationCallback. */
    val codec: MessageCodec<Any?> by lazy {
      MdlPresentationPigeonCodec()
    }
  }
  /** Called when the presentation state changes */
  fun onStateChange(updateArg: MdlPresentationStateUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.sprucekit_mobile.MdlPresentationCallback.onStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(MdlPresentationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MdlPresentationPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * ISO 18013-5 mDL Presentation API
 *
 * Handles close proximity presentation of mDL credentials via BLE
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MdlPresentation {
  /**
   * Initialize a QR code based presentation session
   *
   * @param packId The credential pack ID containing the mDL
   * @param credentialId The credential ID of the mDL to present
   * @return Result indicating success or error
   */
  fun initializeQrPresentation(packId: String, credentialId: String, callback: (Result<MdlPresentationResult>) -> Unit)
  /**
   * Get the current QR code URI for the presentation
   *
   * @return The QR code URI, or null if not in the correct state
   */
  fun getQrCodeUri(): String?
  /**
   * Get the current presentation state
   *
   * @return Current state update with all relevant data
   */
  fun getCurrentState(): MdlPresentationStateUpdate
  /**
   * Submit the user's selection of namespaces/fields to share
   *
   * The map structure is: docType -> namespace -> list of field names
   *
   * @param selectedNamespaces The selected namespaces and fields
   * @return Result indicating success or error
   */
  fun submitNamespaces(selectedNamespaces: Map<String, Map<String, List<String>>>, callback: (Result<MdlPresentationResult>) -> Unit)
  /** Cancel the current presentation session */
  fun cancel()

  companion object {
    /** The codec used by MdlPresentation. */
    val codec: MessageCodec<Any?> by lazy {
      MdlPresentationPigeonCodec()
    }
    /** Sets up an instance of `MdlPresentation` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MdlPresentation?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.initializeQrPresentation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packIdArg = args[0] as String
            val credentialIdArg = args[1] as String
            api.initializeQrPresentation(packIdArg, credentialIdArg) { result: Result<MdlPresentationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MdlPresentationPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MdlPresentationPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.getQrCodeUri$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getQrCodeUri())
            } catch (exception: Throwable) {
              MdlPresentationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.getCurrentState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentState())
            } catch (exception: Throwable) {
              MdlPresentationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.submitNamespaces$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val selectedNamespacesArg = args[0] as Map<String, Map<String, List<String>>>
            api.submitNamespaces(selectedNamespacesArg) { result: Result<MdlPresentationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MdlPresentationPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MdlPresentationPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancel()
              listOf(null)
            } catch (exception: Throwable) {
              MdlPresentationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
