// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.spruceid.sprucekit_mobile

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object Oid4vpPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is Oid4vpFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class Oid4vpFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Options for creating the permission response
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ResponseOptions (
  val shouldStripQuotes: Boolean,
  val forceArraySerialization: Boolean,
  val removeVpPathPrefix: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ResponseOptions {
      val shouldStripQuotes = pigeonVar_list[0] as Boolean
      val forceArraySerialization = pigeonVar_list[1] as Boolean
      val removeVpPathPrefix = pigeonVar_list[2] as Boolean
      return ResponseOptions(shouldStripQuotes, forceArraySerialization, removeVpPathPrefix)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      shouldStripQuotes,
      forceArraySerialization,
      removeVpPathPrefix,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ResponseOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A field requested by the verifier
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RequestedFieldData (
  val id: String,
  val name: String? = null,
  val path: String,
  val required: Boolean,
  val retained: Boolean,
  val purpose: String? = null,
  val inputDescriptorId: String,
  val rawFields: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RequestedFieldData {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val path = pigeonVar_list[2] as String
      val required = pigeonVar_list[3] as Boolean
      val retained = pigeonVar_list[4] as Boolean
      val purpose = pigeonVar_list[5] as String?
      val inputDescriptorId = pigeonVar_list[6] as String
      val rawFields = pigeonVar_list[7] as List<String>
      return RequestedFieldData(id, name, path, required, retained, purpose, inputDescriptorId, rawFields)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      path,
      required,
      retained,
      purpose,
      inputDescriptorId,
      rawFields,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RequestedFieldData) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A credential that can be presented
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PresentableCredentialData (
  val index: Long,
  val credentialId: String,
  val selectiveDisclosable: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PresentableCredentialData {
      val index = pigeonVar_list[0] as Long
      val credentialId = pigeonVar_list[1] as String
      val selectiveDisclosable = pigeonVar_list[2] as Boolean
      return PresentableCredentialData(index, credentialId, selectiveDisclosable)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      credentialId,
      selectiveDisclosable,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PresentableCredentialData) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Information about the permission request
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PermissionRequestInfo (
  val clientId: String? = null,
  val domain: String? = null,
  val purpose: String? = null,
  val isMultiCredentialSelection: Boolean,
  val isMultiCredentialMatching: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionRequestInfo {
      val clientId = pigeonVar_list[0] as String?
      val domain = pigeonVar_list[1] as String?
      val purpose = pigeonVar_list[2] as String?
      val isMultiCredentialSelection = pigeonVar_list[3] as Boolean
      val isMultiCredentialMatching = pigeonVar_list[4] as Boolean
      return PermissionRequestInfo(clientId, domain, purpose, isMultiCredentialSelection, isMultiCredentialMatching)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      domain,
      purpose,
      isMultiCredentialSelection,
      isMultiCredentialMatching,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PermissionRequestInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of OID4VP operations
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class Oid4vpResult 
/**
 * Operation succeeded
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Oid4vpSuccess (
  val message: String? = null
) : Oid4vpResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Oid4vpSuccess {
      val message = pigeonVar_list[0] as String?
      return Oid4vpSuccess(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Oid4vpSuccess) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Operation failed with error
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Oid4vpError (
  val message: String
) : Oid4vpResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Oid4vpError {
      val message = pigeonVar_list[0] as String
      return Oid4vpError(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Oid4vpError) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of handling an authorization request
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class HandleAuthRequestResult 
/**
 * Authorization request handled successfully
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HandleAuthRequestSuccess (
  val credentials: List<PresentableCredentialData>,
  val info: PermissionRequestInfo
) : HandleAuthRequestResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandleAuthRequestSuccess {
      val credentials = pigeonVar_list[0] as List<PresentableCredentialData>
      val info = pigeonVar_list[1] as PermissionRequestInfo
      return HandleAuthRequestSuccess(credentials, info)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      credentials,
      info,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandleAuthRequestSuccess) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Authorization request failed
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HandleAuthRequestError (
  val message: String
) : HandleAuthRequestResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandleAuthRequestError {
      val message = pigeonVar_list[0] as String
      return HandleAuthRequestError(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandleAuthRequestError) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vpPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class Oid4vpPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ResponseOptions.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RequestedFieldData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PresentableCredentialData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionRequestInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Oid4vpSuccess.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Oid4vpError.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandleAuthRequestSuccess.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandleAuthRequestError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ResponseOptions -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RequestedFieldData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PresentableCredentialData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PermissionRequestInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is Oid4vpSuccess -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is Oid4vpError -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is HandleAuthRequestSuccess -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is HandleAuthRequestError -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * OID4VP credential presentation API
 *
 * Handles the OpenID for Verifiable Presentation flow
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface Oid4vp {
  /**
   * Create a holder with credentials for presentation
   *
   * @param credentialPackIds List of credential pack IDs to use
   * @param trustedDids List of trusted DIDs for verification
   * @param keyId The key identifier for signing (will create if doesn't exist)
   * @param contextMap Optional JSON-LD context map
   */
  fun createHolder(credentialPackIds: List<String>, trustedDids: List<String>, keyId: String, contextMap: Map<String, String>?, callback: (Result<Oid4vpResult>) -> Unit)
  /**
   * Handle an authorization request URL
   *
   * @param url The authorization request URL (e.g., "openid4vp://...")
   * @return HandleAuthRequestResult with matching credentials on success
   */
  fun handleAuthorizationRequest(url: String, callback: (Result<HandleAuthRequestResult>) -> Unit)
  /**
   * Get requested fields for a credential
   *
   * @param credentialIndex Index of the credential in the returned list
   * @return List of requested fields for the credential
   */
  fun getRequestedFields(credentialIndex: Long): List<RequestedFieldData>
  /**
   * Submit the presentation response
   *
   * @param selectedCredentialIndices Indices of selected credentials
   * @param selectedFieldPaths List of selected field paths per credential
   * @param options Response configuration options
   */
  fun submitResponse(selectedCredentialIndices: List<Long>, selectedFieldPaths: List<List<String>>, options: ResponseOptions, callback: (Result<Oid4vpResult>) -> Unit)
  /** Cancel and cleanup the current session */
  fun cancel()

  companion object {
    /** The codec used by Oid4vp. */
    val codec: MessageCodec<Any?> by lazy {
      Oid4vpPigeonCodec()
    }
    /** Sets up an instance of `Oid4vp` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: Oid4vp?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.createHolder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialPackIdsArg = args[0] as List<String>
            val trustedDidsArg = args[1] as List<String>
            val keyIdArg = args[2] as String
            val contextMapArg = args[3] as Map<String, String>?
            api.createHolder(credentialPackIdsArg, trustedDidsArg, keyIdArg, contextMapArg) { result: Result<Oid4vpResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vpPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vpPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.handleAuthorizationRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.handleAuthorizationRequest(urlArg) { result: Result<HandleAuthRequestResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vpPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vpPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.getRequestedFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialIndexArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getRequestedFields(credentialIndexArg))
            } catch (exception: Throwable) {
              Oid4vpPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.submitResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val selectedCredentialIndicesArg = args[0] as List<Long>
            val selectedFieldPathsArg = args[1] as List<List<String>>
            val optionsArg = args[2] as ResponseOptions
            api.submitResponse(selectedCredentialIndicesArg, selectedFieldPathsArg, optionsArg) { result: Result<Oid4vpResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vpPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vpPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancel()
              listOf(null)
            } catch (exception: Throwable) {
              Oid4vpPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
