// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.spruceid.sprucekit_mobile

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object Oid4vciPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is Oid4vciFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class Oid4vciFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** DID method for proof of possession */
enum class DidMethod(val raw: Int) {
  JWK(0),
  KEY(1);

  companion object {
    fun ofRaw(raw: Int): DidMethod? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An OID4VCI protocol version the compatibility facade is willing to use.
 *
 * - [v1] OID4VCI 1.0 (final).
 * - [legacy] The legacy draft-13 request shape.
 *
 * Passed as a set of supported versions. An empty list means auto: probe
 * both versions and prefer v1, transparently falling back to legacy if the
 * issuer rejects the v1 request. `[v1, legacy]` is equivalent to auto.
 */
enum class Oid4vciVersion(val raw: Int) {
  V1(0),
  LEGACY(1);

  companion object {
    fun ofRaw(raw: Int): Oid4vciVersion? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Grant type discriminator for an OID4VCI credential offer.
 *
 * Mirrors the Rust `GrantType` enum on `ResolvedCredentialOffer`.
 */
enum class GrantType(val raw: Int) {
  /**
   * Pre-authorized code grant with no transaction code (PIN). No user
   * authorization required beyond the wallet's confirmation.
   */
  PRE_AUTH_CODE_NO_TX_CODE(0),
  /**
   * Pre-authorized code grant requiring a transaction code (PIN) provided
   * out-of-band by the issuer.
   */
  PRE_AUTH_CODE_WITH_TX_CODE(1),
  /** Authorization-code grant requiring the user to sign in via browser. */
  AUTHORIZATION_CODE(2);

  companion object {
    fun ofRaw(raw: Int): GrantType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Input character set for the transaction code.
 *
 * Mirrors the upstream `oid4vci-rs` `InputMode` enum. The OID4VCI spec
 * defines `numeric` as the default when the issuer omits the field.
 */
enum class TxCodeInputMode(val raw: Int) {
  NUMERIC(0),
  TEXT(1);

  companion object {
    fun ofRaw(raw: Int): TxCodeInputMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Options for credential exchange
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Oid4vciExchangeOptions (
  /** Whether to verify the credential after exchange */
  val verifyAfterExchange: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Oid4vciExchangeOptions {
      val verifyAfterExchange = pigeonVar_list[0] as Boolean
      return Oid4vciExchangeOptions(verifyAfterExchange)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      verifyAfterExchange,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Oid4vciExchangeOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Credential received from issuance
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IssuedCredential (
  /** The credential payload as string (JSON, JWT, etc.) */
  val payload: String,
  /** The credential format (e.g., "jwt_vc_json", "ldp_vc", "mso_mdoc") */
  val format: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IssuedCredential {
      val payload = pigeonVar_list[0] as String
      val format = pigeonVar_list[1] as String
      return IssuedCredential(payload, format)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
      format,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is IssuedCredential) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Metadata describing the issuer's transaction code requirements.
 *
 * All fields are optional per OID4VCI §4.1.1. `tx_code: {}` (an empty
 * object) is a valid signal that PIN is required but with no hints.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TxCodeMetadata (
  /** Input character set. `null` ⇒ wallet treats as `numeric` (spec default). */
  val inputMode: TxCodeInputMode? = null,
  /**
   * Expected code length. `null` ⇒ no length hint (free textfield).
   * `<= 0` ⇒ misconfigured issuer; wallet skips the PIN input and sends "".
   */
  val length: Long? = null,
  /**
   * Optional guidance string from the issuer (max 300 chars per spec).
   * Displayed below the localized subtitle when present.
   */
  val description: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TxCodeMetadata {
      val inputMode = pigeonVar_list[0] as TxCodeInputMode?
      val length = pigeonVar_list[1] as Long?
      val description = pigeonVar_list[2] as String?
      return TxCodeMetadata(inputMode, length, description)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inputMode,
      length,
      description,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TxCodeMetadata) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Opaque handle to a server-side OID4VCI session.
 *
 * Created by `acceptOffer`. The `sessionId` is the key into the Kotlin/Swift
 * registry that holds the underlying Rust `Arc<...>` state handle. Callers
 * must call `releaseSession` if the flow is abandoned before terminal.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OfferSession (
  val sessionId: String,
  /**
   * Pre-issuance metadata for the resolved offer. Returned here (rather than
   * requiring a separate `parseOffer` call) because `acceptOffer` performs
   * its own resolve as part of the token exchange. Use this value, not a
   * cached `parseOffer` result, when constructing the UI for the session.
   */
  val metadata: ParsedOfferMetadata
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OfferSession {
      val sessionId = pigeonVar_list[0] as String
      val metadata = pigeonVar_list[1] as ParsedOfferMetadata
      return OfferSession(sessionId, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      metadata,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OfferSession) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Pre-issuance metadata about an OID4VCI offer.
 *
 * Returned by `parseOffer`. Contains everything the wallet needs to render
 * an issuer-details screen before requesting any user authorization.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ParsedOfferMetadata (
  /** The issuer's identifier URL (`credential_issuer` field in OID4VCI metadata). */
  val issuerId: String,
  /**
   * Optional human-readable display name of the issuer, taken from the
   * `display[0].name` field in the issuer metadata. May be null when the
   * issuer does not provide a display name.
   */
  val issuerDisplayName: String? = null,
  /**
   * The credential configuration IDs included in this offer. Multi-credential
   * offers will contain more than one entry.
   */
  val credentialConfigurationIds: List<String>,
  /** The grant type required to complete the issuance. */
  val grantType: GrantType,
  /** Populated only when `grantType == preAuthCodeWithTxCode`. */
  val txCode: TxCodeMetadata? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ParsedOfferMetadata {
      val issuerId = pigeonVar_list[0] as String
      val issuerDisplayName = pigeonVar_list[1] as String?
      val credentialConfigurationIds = pigeonVar_list[2] as List<String>
      val grantType = pigeonVar_list[3] as GrantType
      val txCode = pigeonVar_list[4] as TxCodeMetadata?
      return ParsedOfferMetadata(issuerId, issuerDisplayName, credentialConfigurationIds, grantType, txCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      issuerId,
      issuerDisplayName,
      credentialConfigurationIds,
      grantType,
      txCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ParsedOfferMetadata) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of OID4VCI issuance
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class Oid4vciResult 
/**
 * Issuance succeeded with credentials
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Oid4vciSuccess (
  val credentials: List<IssuedCredential>
) : Oid4vciResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Oid4vciSuccess {
      val credentials = pigeonVar_list[0] as List<IssuedCredential>
      return Oid4vciSuccess(credentials)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      credentials,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Oid4vciSuccess) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Issuance failed with error
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Oid4vciError (
  val message: String
) : Oid4vciResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Oid4vciError {
      val message = pigeonVar_list[0] as String
      return Oid4vciError(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Oid4vciError) {
      return false
    }
    if (this === other) {
      return true
    }
    return Oid4vciPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class Oid4vciPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DidMethod.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Oid4vciVersion.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GrantType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TxCodeInputMode.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Oid4vciExchangeOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IssuedCredential.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TxCodeMetadata.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OfferSession.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ParsedOfferMetadata.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Oid4vciSuccess.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Oid4vciError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DidMethod -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is Oid4vciVersion -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is GrantType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is TxCodeInputMode -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is Oid4vciExchangeOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is IssuedCredential -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is TxCodeMetadata -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is OfferSession -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ParsedOfferMetadata -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is Oid4vciSuccess -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is Oid4vciError -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * OID4VCI credential issuance API
 *
 * Handles the OpenID for Verifiable Credential Issuance flow
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface Oid4vci {
  /**
   * Resolve an OID4VCI credential offer URL and return pre-issuance metadata.
   *
   * Performs the issuer-metadata HTTP fetch but does NOT initiate token
   * exchange or credential request. Safe to call before any user authorization.
   *
   * @param credentialOffer The full credential offer URL.
   * @param supportedVersions The OID4VCI versions to resolve against. An empty
   *   list means auto (probe both, prefer v1 with legacy fallback).
   * @return Pre-issuance metadata describing the issuer and the grant type
   *   the user will need to complete.
   * @throws when the URL is unparseable or the issuer metadata fetch fails.
   */
  fun parseOffer(credentialOffer: String, supportedVersions: List<Oid4vciVersion>, callback: (Result<ParsedOfferMetadata>) -> Unit)
  /**
   * Run the complete OID4VCI issuance flow
   *
   * This method handles:
   * 1. Initiating session with the credential offer
   * 2. Token exchange
   * 3. Proof of possession generation
   * 4. Credential exchange
   *
   * @param credentialOffer The full credential offer URL (e.g., "openid-credential-offer://...")
   * @param clientId The client ID for the wallet
   * @param redirectUrl The redirect URL for the wallet
   * @param keyId The key identifier for signing (will create if doesn't exist)
   * @param didMethod The DID method for proof of possession
   * @param contextMap Optional JSON-LD context map for credential parsing
   * @param supportedVersions The OID4VCI versions to resolve against. An empty
   *   list means auto (probe both, prefer v1 with legacy fallback).
   * @return Oid4vciResult with credentials on success or error message on failure
   */
  fun runIssuance(credentialOffer: String, clientId: String, redirectUrl: String, keyId: String, didMethod: DidMethod, contextMap: Map<String, String>?, supportedVersions: List<Oid4vciVersion>, callback: (Result<Oid4vciResult>) -> Unit)
  /**
   * Resolve the offer URL and complete the token-endpoint exchange.
   *
   * Performs a full `resolveOfferUrl` (which re-fetches issuer metadata)
   * followed by the token endpoint call, returning the session in its
   * post-token state (e.g., `RequiresTxCode` for tx_code grants).
   *
   * The caller does NOT need to call `parseOffer` separately — this call
   * performs its own resolve. The embedded `OfferSession.metadata` reflects
   * the resolve performed here.
   *
   * Returns a stateful session handle keyed into the platform-side registry.
   * Callers must call `releaseSession` if the flow is abandoned before
   * terminal.
   *
   * The `redirectUrl` is stored on the session and consumed by
   * `buildAuthorizationUrl` when the grant is `authorizationCode`. Pass null
   * for grants that do not require a browser sign-in (pre-auth ± tx_code);
   * if a later `buildAuthorizationUrl` is invoked on a session that was
   * created with a null redirect, it returns null.
   *
   * @throws when the offer cannot be resolved or the token request fails.
   */
  fun acceptOffer(credentialOffer: String, clientId: String, keyId: String, didMethod: DidMethod, redirectUrl: String?, supportedVersions: List<Oid4vciVersion>, callback: (Result<OfferSession>) -> Unit)
  /**
   * Submit a transaction code (PIN) and complete the issuance.
   *
   * Returns `Oid4vciSuccess` on success or `Oid4vciError` on any failure
   * (wrong PIN, network, server error). Upstream `oid4vci-rs` erases the
   * OAuth2 error code at the FFI boundary, so we cannot distinguish a
   * wrong PIN from other token-endpoint failures at this layer; all
   * token-endpoint errors surface as `Oid4vciError("authorization failed")`.
   *
   * The session is consumed and removed from the registry in all cases.
   */
  fun continueWithTxCode(sessionId: String, txCode: String, callback: (Result<Oid4vciResult>) -> Unit)
  /**
   * Build the issuer's authorization URL for the browser sign-in step.
   *
   * Returns the fully-formed authorization URL (client_id, redirect_uri,
   * response_type, scope, code_challenge, code_challenge_method, state) for
   * the wallet to hand to a system-managed browser surface.
   *
   * Returns null when the session is not in the authorization-code state,
   * when the session was created without a `redirectUrl`, or when URL
   * construction fails (e.g., issuer metadata fetch error).
   *
   * The session is preserved on success — the caller must follow up with
   * `continueWithAuthorizationCode` or `releaseSession`.
   */
  fun buildAuthorizationUrl(sessionId: String, callback: (Result<String?>) -> Unit)
  /**
   * Submit the authorization code returned by the issuer redirect and
   * complete the issuance.
   *
   * Returns `Oid4vciSuccess` on success or `Oid4vciError` for any failure
   * (token endpoint, state mismatch, network). Same upstream-error-erasure
   * constraint as `continueWithTxCode` applies — callers cannot distinguish
   * underlying causes at this layer.
   *
   * The session is consumed and removed from the registry in all cases.
   */
  fun continueWithAuthorizationCode(sessionId: String, code: String, callback: (Result<Oid4vciResult>) -> Unit)
  /**
   * Drop a session without consuming it (user abort).
   *
   * Safe to call with an unknown sessionId — no-op.
   */
  fun releaseSession(sessionId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by Oid4vci. */
    val codec: MessageCodec<Any?> by lazy {
      Oid4vciPigeonCodec()
    }
    /** Sets up an instance of `Oid4vci` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: Oid4vci?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.parseOffer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialOfferArg = args[0] as String
            val supportedVersionsArg = args[1] as List<Oid4vciVersion>
            api.parseOffer(credentialOfferArg, supportedVersionsArg) { result: Result<ParsedOfferMetadata> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vciPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.runIssuance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialOfferArg = args[0] as String
            val clientIdArg = args[1] as String
            val redirectUrlArg = args[2] as String
            val keyIdArg = args[3] as String
            val didMethodArg = args[4] as DidMethod
            val contextMapArg = args[5] as Map<String, String>?
            val supportedVersionsArg = args[6] as List<Oid4vciVersion>
            api.runIssuance(credentialOfferArg, clientIdArg, redirectUrlArg, keyIdArg, didMethodArg, contextMapArg, supportedVersionsArg) { result: Result<Oid4vciResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vciPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.acceptOffer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialOfferArg = args[0] as String
            val clientIdArg = args[1] as String
            val keyIdArg = args[2] as String
            val didMethodArg = args[3] as DidMethod
            val redirectUrlArg = args[4] as String?
            val supportedVersionsArg = args[5] as List<Oid4vciVersion>
            api.acceptOffer(credentialOfferArg, clientIdArg, keyIdArg, didMethodArg, redirectUrlArg, supportedVersionsArg) { result: Result<OfferSession> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vciPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.continueWithTxCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val txCodeArg = args[1] as String
            api.continueWithTxCode(sessionIdArg, txCodeArg) { result: Result<Oid4vciResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vciPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.buildAuthorizationUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.buildAuthorizationUrl(sessionIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vciPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.continueWithAuthorizationCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val codeArg = args[1] as String
            api.continueWithAuthorizationCode(sessionIdArg, codeArg) { result: Result<Oid4vciResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Oid4vciPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.releaseSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.releaseSession(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Oid4vciPigeonUtils.wrapError(error))
              } else {
                reply.reply(Oid4vciPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
