// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.spruceid.sprucekit_mobile

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SpruceUtilsPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is SpruceUtilsFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class SpruceUtilsFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * The type of a PDF supplement.
 *
 * New supplement types can be added here without changing the function
 * signature of `generateCredentialPdf`.
 */
enum class PdfSupplementType(val raw: Int) {
  BARCODE(0);

  companion object {
    fun ofRaw(raw: Int): PdfSupplementType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Barcode type for PDF supplements */
enum class PdfBarcodeType(val raw: Int) {
  QR_CODE(0),
  PDF417(1);

  companion object {
    fun ofRaw(raw: Int): PdfBarcodeType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Result of generating a mock mDL
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class GenerateMockMdlResult 
/**
 * Mock mDL generated successfully - stored in a CredentialPack
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GenerateMockMdlSuccess (
  /** The credential pack ID where the mDL was stored */
  val packId: String,
  /** The credential ID of the generated mDL */
  val credentialId: String,
  /** The raw mSO mDoc as base64 string for storage */
  val rawCredential: String,
  /** The key alias used for signing */
  val keyAlias: String
) : GenerateMockMdlResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GenerateMockMdlSuccess {
      val packId = pigeonVar_list[0] as String
      val credentialId = pigeonVar_list[1] as String
      val rawCredential = pigeonVar_list[2] as String
      val keyAlias = pigeonVar_list[3] as String
      return GenerateMockMdlSuccess(packId, credentialId, rawCredential, keyAlias)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packId,
      credentialId,
      rawCredential,
      keyAlias,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GenerateMockMdlSuccess
    return SpruceUtilsPigeonUtils.deepEquals(this.packId, other.packId) && SpruceUtilsPigeonUtils.deepEquals(this.credentialId, other.credentialId) && SpruceUtilsPigeonUtils.deepEquals(this.rawCredential, other.rawCredential) && SpruceUtilsPigeonUtils.deepEquals(this.keyAlias, other.keyAlias)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.packId)
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.credentialId)
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.rawCredential)
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.keyAlias)
    return result
  }
}

/**
 * Mock mDL generation failed
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GenerateMockMdlError (
  val message: String
) : GenerateMockMdlResult()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GenerateMockMdlError {
      val message = pigeonVar_list[0] as String
      return GenerateMockMdlError(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GenerateMockMdlError
    return SpruceUtilsPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.message)
    return result
  }
}

/**
 * A supplement to include in the generated PDF.
 *
 * This is an extensible carrier: the `type` field determines which optional
 * fields are relevant.  Adding a new supplement kind only requires a new
 * [PdfSupplementType] value and new optional fields — the API signature
 * stays the same.
 *
 * **Barcode** (`type == PdfSupplementType.barcode`):
 *   - `data` — raw bytes to encode (e.g. VP Token, AAMVA payload)
 *   - `barcodeType` — QR Code or PDF-417
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PdfSupplement (
  val type: PdfSupplementType,
  /** Raw bytes to encode as a barcode. Required when `type` is `barcode`. */
  val data: ByteArray? = null,
  /** The barcode symbology. Required when `type` is `barcode`. */
  val barcodeType: PdfBarcodeType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PdfSupplement {
      val type = pigeonVar_list[0] as PdfSupplementType
      val data = pigeonVar_list[1] as ByteArray?
      val barcodeType = pigeonVar_list[2] as PdfBarcodeType?
      return PdfSupplement(type, data, barcodeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      data,
      barcodeType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PdfSupplement
    return SpruceUtilsPigeonUtils.deepEquals(this.type, other.type) && SpruceUtilsPigeonUtils.deepEquals(this.data, other.data) && SpruceUtilsPigeonUtils.deepEquals(this.barcodeType, other.barcodeType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.type)
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.data)
    result = 31 * result + SpruceUtilsPigeonUtils.deepHash(this.barcodeType)
    return result
  }
}
private open class SpruceUtilsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PdfSupplementType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PdfBarcodeType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GenerateMockMdlSuccess.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GenerateMockMdlError.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PdfSupplement.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PdfSupplementType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PdfBarcodeType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is GenerateMockMdlSuccess -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is GenerateMockMdlError -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PdfSupplement -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Utility functions for credential operations
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SpruceUtils {
  /**
   * Generate a mock mDL for testing
   *
   * Creates a self-signed test mDL credential and stores it in a new
   * CredentialPack. The returned packId and credentialId can be used with
   * MdlPresentation.initializeQrPresentation().
   *
   * @param keyAlias Optional key alias to use (defaults to "testMdl")
   * @return Result with packId, credentialId, rawCredential, and keyAlias, or error
   */
  fun generateMockMdl(keyAlias: String?, callback: (Result<GenerateMockMdlResult>) -> Unit)
  /**
   * Generate a PDF from a raw mDL credential.
   *
   * Accepts the raw mSO mDoc as a base64url-encoded IssuerSigned string
   * (the same format returned by generateMockMdl's rawCredential field).
   *
   * @param rawMdoc Base64url-encoded IssuerSigned bytes of the mDL
   * @param supplements Optional list of supplements to include in the PDF
   * @return Raw PDF bytes ready to write to a file and share
   */
  fun generateCredentialPdf(rawMdoc: String, supplements: List<PdfSupplement>, callback: (Result<ByteArray>) -> Unit)

  companion object {
    /** The codec used by SpruceUtils. */
    val codec: MessageCodec<Any?> by lazy {
      SpruceUtilsPigeonCodec()
    }
    /** Sets up an instance of `SpruceUtils` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SpruceUtils?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateMockMdl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            api.generateMockMdl(keyAliasArg) { result: Result<GenerateMockMdlResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SpruceUtilsPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SpruceUtilsPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateCredentialPdf$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val rawMdocArg = args[0] as String
            val supplementsArg = args[1] as List<PdfSupplement>
            api.generateCredentialPdf(rawMdocArg, supplementsArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SpruceUtilsPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SpruceUtilsPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
