// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Credential status from status list
enum CredentialStatus {
  valid,
  revoked,
  suspended,
  unknown,
  invalid,
  undefined,
  pending,
  ready,
}

/// Credential format type
enum CredentialFormat {
  jwtVc,
  jsonVc,
  sdJwt,
  msoMdoc,
  cwt,
}

/// A parsed credential with its metadata
class ParsedCredentialData {
  ParsedCredentialData({
    required this.id,
    required this.format,
    required this.rawCredential,
  });

  /// Unique identifier for this credential
  String id;

  /// The credential format
  CredentialFormat format;

  /// Raw credential data as string
  String rawCredential;

  List<Object?> _toList() {
    return <Object?>[
      id,
      format,
      rawCredential,
    ];
  }

  Object encode() {
    return _toList();  }

  static ParsedCredentialData decode(Object result) {
    result as List<Object?>;
    return ParsedCredentialData(
      id: result[0]! as String,
      format: result[1]! as CredentialFormat,
      rawCredential: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ParsedCredentialData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// A credential pack with its credentials
class CredentialPackData {
  CredentialPackData({
    required this.id,
    required this.credentials,
  });

  /// Unique identifier for this pack
  String id;

  /// List of credentials in this pack
  List<ParsedCredentialData> credentials;

  List<Object?> _toList() {
    return <Object?>[
      id,
      credentials,
    ];
  }

  Object encode() {
    return _toList();  }

  static CredentialPackData decode(Object result) {
    result as List<Object?>;
    return CredentialPackData(
      id: result[0]! as String,
      credentials: (result[1] as List<Object?>?)!.cast<ParsedCredentialData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CredentialPackData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Result types for credential operations
sealed class CredentialOperationResult {
}

/// Operation succeeded
class CredentialOperationSuccess extends CredentialOperationResult {
  CredentialOperationSuccess({
    this.unused,
  });

  int? unused;

  List<Object?> _toList() {
    return <Object?>[
      unused,
    ];
  }

  Object encode() {
    return _toList();  }

  static CredentialOperationSuccess decode(Object result) {
    result as List<Object?>;
    return CredentialOperationSuccess(
      unused: result[0] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CredentialOperationSuccess || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Operation failed with error message
class CredentialOperationError extends CredentialOperationResult {
  CredentialOperationError({
    required this.message,
  });

  String message;

  List<Object?> _toList() {
    return <Object?>[
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static CredentialOperationError decode(Object result) {
    result as List<Object?>;
    return CredentialOperationError(
      message: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CredentialOperationError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Result of adding a credential
sealed class AddCredentialResult {
}

/// Adding credential succeeded
class AddCredentialSuccess extends AddCredentialResult {
  AddCredentialSuccess({
    required this.credentials,
  });

  /// The updated list of credentials in the pack
  List<ParsedCredentialData> credentials;

  List<Object?> _toList() {
    return <Object?>[
      credentials,
    ];
  }

  Object encode() {
    return _toList();  }

  static AddCredentialSuccess decode(Object result) {
    result as List<Object?>;
    return AddCredentialSuccess(
      credentials: (result[0] as List<Object?>?)!.cast<ParsedCredentialData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AddCredentialSuccess || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Adding credential failed
class AddCredentialError extends AddCredentialResult {
  AddCredentialError({
    required this.message,
  });

  String message;

  List<Object?> _toList() {
    return <Object?>[
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static AddCredentialError decode(Object result) {
    result as List<Object?>;
    return AddCredentialError(
      message: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AddCredentialError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CredentialStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CredentialFormat) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ParsedCredentialData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CredentialPackData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CredentialOperationSuccess) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is CredentialOperationError) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is AddCredentialSuccess) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is AddCredentialError) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CredentialStatus.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CredentialFormat.values[value];
      case 131: 
        return ParsedCredentialData.decode(readValue(buffer)!);
      case 132: 
        return CredentialPackData.decode(readValue(buffer)!);
      case 133: 
        return CredentialOperationSuccess.decode(readValue(buffer)!);
      case 134: 
        return CredentialOperationError.decode(readValue(buffer)!);
      case 135: 
        return AddCredentialSuccess.decode(readValue(buffer)!);
      case 136: 
        return AddCredentialError.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// CredentialPack management API
///
/// Manages collections of credentials with parsing and storage capabilities
class CredentialPack {
  /// Constructor for [CredentialPack].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CredentialPack({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Create a new empty credential pack
  ///
  /// @return The pack ID
  Future<String> createPack() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.createPack$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Get a credential pack by ID
  ///
  /// @param packId The pack identifier
  /// @return The credential pack data, or null if not found
  Future<CredentialPackData?> getPack(String packId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.getPack$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as CredentialPackData?);
    }
  }

  /// Add a raw credential to a pack (auto-detects format)
  ///
  /// Tries to parse the credential as: JWT VC, JSON VC, SD-JWT, or CWT
  ///
  /// @param packId The pack identifier
  /// @param rawCredential The raw credential string
  /// @return AddCredentialResult with updated credentials or error
  Future<AddCredentialResult> addRawCredential(String packId, String rawCredential) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.addRawCredential$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId, rawCredential]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as AddCredentialResult?)!;
    }
  }

  /// Add a raw mDoc credential to a pack
  ///
  /// @param packId The pack identifier
  /// @param rawCredential The raw mDoc credential
  /// @param keyAlias The key alias to use for the mDoc
  /// @return AddCredentialResult with updated credentials or error
  Future<AddCredentialResult> addRawMdoc(String packId, String rawCredential, String keyAlias) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.addRawMdoc$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId, rawCredential, keyAlias]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as AddCredentialResult?)!;
    }
  }

  /// Add a credential in any supported format
  ///
  /// Tries standard formats first, then mDoc with the provided key alias
  ///
  /// @param packId The pack identifier
  /// @param rawCredential The raw credential string
  /// @param mdocKeyAlias The key alias to use if parsing as mDoc
  /// @return AddCredentialResult with updated credentials or error
  Future<AddCredentialResult> addAnyFormat(String packId, String rawCredential, String mdocKeyAlias) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.addAnyFormat$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId, rawCredential, mdocKeyAlias]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as AddCredentialResult?)!;
    }
  }

  /// Get all credentials in a pack
  ///
  /// @param packId The pack identifier
  /// @return List of credentials, empty if pack not found
  Future<List<ParsedCredentialData>> listCredentials(String packId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.listCredentials$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ParsedCredentialData>();
    }
  }

  /// Get credential claims
  ///
  /// @param packId The pack identifier
  /// @param credentialId The credential identifier
  /// @param claimNames Optional list of claim names to filter (empty = all claims)
  /// @return JSON string of claims, or null if not found
  Future<String?> getCredentialClaims(String packId, String credentialId, List<String> claimNames) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.getCredentialClaims$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId, credentialId, claimNames]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// Delete a credential pack
  ///
  /// @param packId The pack identifier
  /// @return CredentialOperationResult indicating success or error
  Future<CredentialOperationResult> deletePack(String packId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.deletePack$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CredentialOperationResult?)!;
    }
  }

  /// Get all credential pack IDs
  ///
  /// @return List of pack IDs
  Future<List<String>> listPacks() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.CredentialPack.listPacks$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }
}
