// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// A field requested by the verifier for mDoc presentation
class RequestedField180137Data {
  RequestedField180137Data({
    required this.id,
    required this.displayableName,
    this.displayableValue,
    required this.selectivelyDisclosable,
    required this.intentToRetain,
    required this.required,
    this.purpose,
  });

  /// Field identifier (namespace + element name)
  String id;

  /// Human-readable display name
  String displayableName;

  /// Current value of the field (if available)
  String? displayableValue;

  /// Whether this field can be selectively disclosed
  bool selectivelyDisclosable;

  /// Whether the verifier intends to retain this data
  bool intentToRetain;

  /// Whether this field is required by the verifier
  bool required;

  /// Purpose description for requesting this field
  String? purpose;

  List<Object?> _toList() {
    return <Object?>[
      id,
      displayableName,
      displayableValue,
      selectivelyDisclosable,
      intentToRetain,
      required,
      purpose,
    ];
  }

  Object encode() {
    return _toList();  }

  static RequestedField180137Data decode(Object result) {
    result as List<Object?>;
    return RequestedField180137Data(
      id: result[0]! as String,
      displayableName: result[1]! as String,
      displayableValue: result[2] as String?,
      selectivelyDisclosable: result[3]! as bool,
      intentToRetain: result[4]! as bool,
      required: result[5]! as bool,
      purpose: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RequestedField180137Data || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// A matching credential for the OID4VP request
class RequestMatch180137Data {
  RequestMatch180137Data({
    required this.index,
    required this.credentialId,
    required this.requestedFields,
  });

  /// Index in the matches list
  int index;

  /// Credential ID (UUID as string)
  String credentialId;

  /// Fields requested for this credential
  List<RequestedField180137Data> requestedFields;

  List<Object?> _toList() {
    return <Object?>[
      index,
      credentialId,
      requestedFields,
    ];
  }

  Object encode() {
    return _toList();  }

  static RequestMatch180137Data decode(Object result) {
    result as List<Object?>;
    return RequestMatch180137Data(
      index: result[0]! as int,
      credentialId: result[1]! as String,
      requestedFields: (result[2] as List<Object?>?)!.cast<RequestedField180137Data>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RequestMatch180137Data || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Information about the OID4VP request
class Oid4vpMdocRequestInfo {
  Oid4vpMdocRequestInfo({
    this.requestedBy,
    required this.matches,
  });

  /// Name of the verifier requesting the credential
  String? requestedBy;

  /// List of matching credentials
  List<RequestMatch180137Data> matches;

  List<Object?> _toList() {
    return <Object?>[
      requestedBy,
      matches,
    ];
  }

  Object encode() {
    return _toList();  }

  static Oid4vpMdocRequestInfo decode(Object result) {
    result as List<Object?>;
    return Oid4vpMdocRequestInfo(
      requestedBy: result[0] as String?,
      matches: (result[1] as List<Object?>?)!.cast<RequestMatch180137Data>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Oid4vpMdocRequestInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Result of OID4VP mDoc operations
sealed class Oid4vpMdocResult {
}

/// Operation succeeded
class Oid4vpMdocSuccess extends Oid4vpMdocResult {
  Oid4vpMdocSuccess({
    this.message,
    this.redirectUrl,
  });

  String? message;

  /// Redirect URL (if any) returned after successful presentation
  String? redirectUrl;

  List<Object?> _toList() {
    return <Object?>[
      message,
      redirectUrl,
    ];
  }

  Object encode() {
    return _toList();  }

  static Oid4vpMdocSuccess decode(Object result) {
    result as List<Object?>;
    return Oid4vpMdocSuccess(
      message: result[0] as String?,
      redirectUrl: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Oid4vpMdocSuccess || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Operation failed with error
class Oid4vpMdocError extends Oid4vpMdocResult {
  Oid4vpMdocError({
    required this.message,
  });

  String message;

  List<Object?> _toList() {
    return <Object?>[
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static Oid4vpMdocError decode(Object result) {
    result as List<Object?>;
    return Oid4vpMdocError(
      message: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Oid4vpMdocError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Result of processing an authorization request
sealed class ProcessRequestResult {
}

/// Request processed successfully
class ProcessRequestSuccess extends ProcessRequestResult {
  ProcessRequestSuccess({
    required this.info,
  });

  Oid4vpMdocRequestInfo info;

  List<Object?> _toList() {
    return <Object?>[
      info,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProcessRequestSuccess decode(Object result) {
    result as List<Object?>;
    return ProcessRequestSuccess(
      info: result[0]! as Oid4vpMdocRequestInfo,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProcessRequestSuccess || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request processing failed
class ProcessRequestError extends ProcessRequestResult {
  ProcessRequestError({
    required this.message,
  });

  String message;

  List<Object?> _toList() {
    return <Object?>[
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static ProcessRequestError decode(Object result) {
    result as List<Object?>;
    return ProcessRequestError(
      message: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProcessRequestError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RequestedField180137Data) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is RequestMatch180137Data) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is Oid4vpMdocRequestInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is Oid4vpMdocSuccess) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is Oid4vpMdocError) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ProcessRequestSuccess) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ProcessRequestError) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return RequestedField180137Data.decode(readValue(buffer)!);
      case 130: 
        return RequestMatch180137Data.decode(readValue(buffer)!);
      case 131: 
        return Oid4vpMdocRequestInfo.decode(readValue(buffer)!);
      case 132: 
        return Oid4vpMdocSuccess.decode(readValue(buffer)!);
      case 133: 
        return Oid4vpMdocError.decode(readValue(buffer)!);
      case 134: 
        return ProcessRequestSuccess.decode(readValue(buffer)!);
      case 135: 
        return ProcessRequestError.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// OID4VP mDoc presentation API (ISO 18013-7)
///
/// Handles OpenID for Verifiable Presentation with mDoc credentials
/// using the mdoc-openid4vp:// URI scheme
class Oid4vpMdoc {
  /// Constructor for [Oid4vpMdoc].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  Oid4vpMdoc({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Initialize the handler with mDoc credentials from credential packs
  ///
  /// @param credentialPackIds List of credential pack IDs containing mDocs
  /// @return Result indicating success or error
  Future<Oid4vpMdocResult> initialize(List<String> credentialPackIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.Oid4vpMdoc.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[credentialPackIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Oid4vpMdocResult?)!;
    }
  }

  /// Process an authorization request URL
  ///
  /// @param url The authorization request URL (mdoc-openid4vp://...)
  /// @return ProcessRequestResult with matching credentials on success
  Future<ProcessRequestResult> processRequest(String url) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.Oid4vpMdoc.processRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ProcessRequestResult?)!;
    }
  }

  /// Submit the presentation response
  ///
  /// @param matchIndex Index of the selected credential match
  /// @param approvedFieldIds List of approved field IDs to share
  /// @return Result with redirect URL on success
  Future<Oid4vpMdocResult> submitResponse(int matchIndex, List<String> approvedFieldIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.Oid4vpMdoc.submitResponse$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[matchIndex, approvedFieldIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Oid4vpMdocResult?)!;
    }
  }

  /// Cancel and cleanup the current session
  Future<void> cancel() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.Oid4vpMdoc.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
