// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// The type of a PDF supplement.
///
/// New supplement types can be added here without changing the function
/// signature of `generateCredentialPdf`.
enum PdfSupplementType {
  barcode,
}

/// Barcode type for PDF supplements
enum PdfBarcodeType {
  qrCode,
  pdf417,
}

/// Result of generating a mock mDL
sealed class GenerateMockMdlResult {
}

/// Mock mDL generated successfully - stored in a CredentialPack
class GenerateMockMdlSuccess extends GenerateMockMdlResult {
  GenerateMockMdlSuccess({
    required this.packId,
    required this.credentialId,
    required this.rawCredential,
    required this.keyAlias,
  });

  /// The credential pack ID where the mDL was stored
  String packId;

  /// The credential ID of the generated mDL
  String credentialId;

  /// The raw mSO mDoc as base64 string for storage
  String rawCredential;

  /// The key alias used for signing
  String keyAlias;

  List<Object?> _toList() {
    return <Object?>[
      packId,
      credentialId,
      rawCredential,
      keyAlias,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerateMockMdlSuccess decode(Object result) {
    result as List<Object?>;
    return GenerateMockMdlSuccess(
      packId: result[0]! as String,
      credentialId: result[1]! as String,
      rawCredential: result[2]! as String,
      keyAlias: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerateMockMdlSuccess || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packId, other.packId) && _deepEquals(credentialId, other.credentialId) && _deepEquals(rawCredential, other.rawCredential) && _deepEquals(keyAlias, other.keyAlias);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Mock mDL generation failed
class GenerateMockMdlError extends GenerateMockMdlResult {
  GenerateMockMdlError({
    required this.message,
  });

  String message;

  List<Object?> _toList() {
    return <Object?>[
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerateMockMdlError decode(Object result) {
    result as List<Object?>;
    return GenerateMockMdlError(
      message: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerateMockMdlError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A supplement to include in the generated PDF.
///
/// This is an extensible carrier: the `type` field determines which optional
/// fields are relevant.  Adding a new supplement kind only requires a new
/// [PdfSupplementType] value and new optional fields — the API signature
/// stays the same.
///
/// **Barcode** (`type == PdfSupplementType.barcode`):
///   - `data` — raw bytes to encode (e.g. VP Token, AAMVA payload)
///   - `barcodeType` — QR Code or PDF-417
class PdfSupplement {
  PdfSupplement({
    required this.type,
    this.data,
    this.barcodeType,
  });

  PdfSupplementType type;

  /// Raw bytes to encode as a barcode. Required when `type` is `barcode`.
  Uint8List? data;

  /// The barcode symbology. Required when `type` is `barcode`.
  PdfBarcodeType? barcodeType;

  List<Object?> _toList() {
    return <Object?>[
      type,
      data,
      barcodeType,
    ];
  }

  Object encode() {
    return _toList();  }

  static PdfSupplement decode(Object result) {
    result as List<Object?>;
    return PdfSupplement(
      type: result[0]! as PdfSupplementType,
      data: result[1] as Uint8List?,
      barcodeType: result[2] as PdfBarcodeType?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfSupplement || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(data, other.data) && _deepEquals(barcodeType, other.barcodeType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PdfSupplementType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PdfBarcodeType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is GenerateMockMdlSuccess) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is GenerateMockMdlError) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PdfSupplement) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfSupplementType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfBarcodeType.values[value];
      case 131:
        return GenerateMockMdlSuccess.decode(readValue(buffer)!);
      case 132:
        return GenerateMockMdlError.decode(readValue(buffer)!);
      case 133:
        return PdfSupplement.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Utility functions for credential operations
class SpruceUtils {
  /// Constructor for [SpruceUtils].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SpruceUtils({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generate a mock mDL for testing
  ///
  /// Creates a self-signed test mDL credential and stores it in a new
  /// CredentialPack. The returned packId and credentialId can be used with
  /// MdlPresentation.initializeQrPresentation().
  ///
  /// @param keyAlias Optional key alias to use (defaults to "testMdl")
  /// @return Result with packId, credentialId, rawCredential, and keyAlias, or error
  Future<GenerateMockMdlResult> generateMockMdl(String? keyAlias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateMockMdl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GenerateMockMdlResult;
  }

  /// Generate a PDF from a raw mDL credential.
  ///
  /// Accepts the raw mSO mDoc as a base64url-encoded IssuerSigned string
  /// (the same format returned by generateMockMdl's rawCredential field).
  ///
  /// @param rawMdoc Base64url-encoded IssuerSigned bytes of the mDL
  /// @param supplements Optional list of supplements to include in the PDF
  /// @return Raw PDF bytes ready to write to a file and share
  Future<Uint8List> generateCredentialPdf(String rawMdoc, List<PdfSupplement> supplements) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateCredentialPdf$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[rawMdoc, supplements]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }
}
