// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class MdlPresentationPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "MdlPresentationPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? MdlPresentationPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> MdlPresentationPigeonError {
  return MdlPresentationPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMdlPresentation(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMdlPresentation(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMdlPresentation(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMdlPresentation(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMdlPresentation(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMdlPresentation(lhsKey, rhsKey) {
          if deepEqualsMdlPresentation(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMdlPresentation(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMdlPresentation(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMdlPresentation(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMdlPresentation(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMdlPresentation(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMdlPresentation(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMdlPresentation(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Presentation state for ISO 18013-5 mDL presentation
///
/// Migration note: an NFC tap based presentation reports its NFC detail in
/// [MdlPresentationStateUpdate.nfcPhase] and keeps this enum unchanged, so
/// existing exhaustive switches still compile. The next major release merges
/// the phases into this enum as `nfcWaitingForTap`, `connectingViaNfc` and
/// `nfcUnavailable`, and removes `nfcPhase`. Code that reads the NFC detail
/// through the `MdlPresentationStateUpdate` getters (`isWaitingForNfcTap`,
/// `isConnectingViaNfc`, `isNfcUnavailable`) needs no change at that point.
enum MdlPresentationState: Int {
  /// Initial state, not yet started
  case uninitialized = 0
  /// Waiting for Bluetooth/transport to be ready
  case initializing = 1
  /// Bluetooth needs to be turned on to continue
  case bluetoothRequired = 2
  /// Bluetooth authorization required in Settings
  case bluetoothAuthorizationRequired = 3
  /// QR code is ready to be displayed
  case engagingQrCode = 4
  /// Reader has connected, waiting for request
  case connected = 5
  /// Received request from reader, user needs to select fields
  case selectingNamespaces = 6
  /// Sending response to reader
  case sendingResponse = 7
  /// Successfully sent response
  case success = 8
  /// Session timed out
  case timeout = 9
  /// Reader disconnected unexpectedly
  case readerDisconnected = 10
  /// An error occurred
  case error = 11
}

/// Where an NFC tap based presentation is, on top of [MdlPresentationState]
///
/// Only set on Android after [MdlPresentation.initializeNfcPresentation].
/// The main state stays within the existing values, so callers that do not
/// know about NFC keep working: `initializing` while the tap is pending and
/// `error` when NFC is turned off.
///
/// Transitional. The next major release folds these values into
/// [MdlPresentationState] and removes this enum. Read the phase through the
/// `MdlPresentationStateUpdate` getters, not through this enum, to stay
/// unaffected by that change.
enum MdlNfcPhase: Int {
  /// The phone answers reader taps. State is `initializing`.
  case waitingForTap = 0
  /// The tap delivered the BLE carrier. Connection in progress. State is
  /// `initializing`.
  case connecting = 1
  /// NFC was turned off while waiting. State is `error`. Fall back to QR.
  case unavailable = 2
}

/// Requested item from a namespace
///
/// Generated class from Pigeon that represents data sent in messages.
struct MdlNamespaceItem: Hashable {
  /// Field name
  var name: String
  /// Whether the field is required by the reader
  var intentToRetain: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MdlNamespaceItem? {
    let name = pigeonVar_list[0] as! String
    let intentToRetain = pigeonVar_list[1] as! Bool

    return MdlNamespaceItem(
      name: name,
      intentToRetain: intentToRetain
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      intentToRetain,
    ]
  }
  static func == (lhs: MdlNamespaceItem, rhs: MdlNamespaceItem) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMdlPresentation(lhs.name, rhs.name) && deepEqualsMdlPresentation(lhs.intentToRetain, rhs.intentToRetain)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MdlNamespaceItem")
    deepHashMdlPresentation(value: name, hasher: &hasher)
    deepHashMdlPresentation(value: intentToRetain, hasher: &hasher)
  }
}

/// Request from reader for a specific namespace
///
/// Generated class from Pigeon that represents data sent in messages.
struct MdlNamespaceRequest: Hashable {
  /// Namespace identifier (e.g., "org.iso.18013.5.1")
  var namespace: String
  /// Items requested in this namespace
  var items: [MdlNamespaceItem]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MdlNamespaceRequest? {
    let namespace = pigeonVar_list[0] as! String
    let items = pigeonVar_list[1] as! [MdlNamespaceItem]

    return MdlNamespaceRequest(
      namespace: namespace,
      items: items
    )
  }
  func toList() -> [Any?] {
    return [
      namespace,
      items,
    ]
  }
  static func == (lhs: MdlNamespaceRequest, rhs: MdlNamespaceRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMdlPresentation(lhs.namespace, rhs.namespace) && deepEqualsMdlPresentation(lhs.items, rhs.items)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MdlNamespaceRequest")
    deepHashMdlPresentation(value: namespace, hasher: &hasher)
    deepHashMdlPresentation(value: items, hasher: &hasher)
  }
}

/// Items request from reader for a specific docType
///
/// Generated class from Pigeon that represents data sent in messages.
struct MdlItemsRequest: Hashable {
  /// Document type (e.g., "org.iso.18013.5.1.mDL")
  var docType: String
  /// Namespaces and their requested items
  var namespaces: [MdlNamespaceRequest]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MdlItemsRequest? {
    let docType = pigeonVar_list[0] as! String
    let namespaces = pigeonVar_list[1] as! [MdlNamespaceRequest]

    return MdlItemsRequest(
      docType: docType,
      namespaces: namespaces
    )
  }
  func toList() -> [Any?] {
    return [
      docType,
      namespaces,
    ]
  }
  static func == (lhs: MdlItemsRequest, rhs: MdlItemsRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMdlPresentation(lhs.docType, rhs.docType) && deepEqualsMdlPresentation(lhs.namespaces, rhs.namespaces)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MdlItemsRequest")
    deepHashMdlPresentation(value: docType, hasher: &hasher)
    deepHashMdlPresentation(value: namespaces, hasher: &hasher)
  }
}

/// State update event from the presentation session
///
/// Generated class from Pigeon that represents data sent in messages.
struct MdlPresentationStateUpdate: Hashable {
  /// Current state
  var state: MdlPresentationState
  /// QR code URI (only set when state is engagingQrCode)
  var qrCodeUri: String? = nil
  /// Items requests from reader (only set when state is selectingNamespaces)
  var itemsRequests: [MdlItemsRequest]? = nil
  /// Error message (only set when state is error)
  var error: String? = nil
  /// NFC detail for an NFC tap based presentation (Android only)
  ///
  /// Transitional field, see [MdlNfcPhase]. Prefer the getters
  /// `isWaitingForNfcTap`, `isConnectingViaNfc` and `isNfcUnavailable`.
  var nfcPhase: MdlNfcPhase? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MdlPresentationStateUpdate? {
    let state = pigeonVar_list[0] as! MdlPresentationState
    let qrCodeUri: String? = nilOrValue(pigeonVar_list[1])
    let itemsRequests: [MdlItemsRequest]? = nilOrValue(pigeonVar_list[2])
    let error: String? = nilOrValue(pigeonVar_list[3])
    let nfcPhase: MdlNfcPhase? = nilOrValue(pigeonVar_list[4])

    return MdlPresentationStateUpdate(
      state: state,
      qrCodeUri: qrCodeUri,
      itemsRequests: itemsRequests,
      error: error,
      nfcPhase: nfcPhase
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      qrCodeUri,
      itemsRequests,
      error,
      nfcPhase,
    ]
  }
  static func == (lhs: MdlPresentationStateUpdate, rhs: MdlPresentationStateUpdate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMdlPresentation(lhs.state, rhs.state) && deepEqualsMdlPresentation(lhs.qrCodeUri, rhs.qrCodeUri) && deepEqualsMdlPresentation(lhs.itemsRequests, rhs.itemsRequests) && deepEqualsMdlPresentation(lhs.error, rhs.error) && deepEqualsMdlPresentation(lhs.nfcPhase, rhs.nfcPhase)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MdlPresentationStateUpdate")
    deepHashMdlPresentation(value: state, hasher: &hasher)
    deepHashMdlPresentation(value: qrCodeUri, hasher: &hasher)
    deepHashMdlPresentation(value: itemsRequests, hasher: &hasher)
    deepHashMdlPresentation(value: error, hasher: &hasher)
    deepHashMdlPresentation(value: nfcPhase, hasher: &hasher)
  }
}

/// Result type for presentation operations
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol MdlPresentationResult {

}

/// Operation succeeded
///
/// Generated class from Pigeon that represents data sent in messages.
struct MdlPresentationSuccess: MdlPresentationResult {
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MdlPresentationSuccess? {
    let message: String? = nilOrValue(pigeonVar_list[0])

    return MdlPresentationSuccess(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: MdlPresentationSuccess, rhs: MdlPresentationSuccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMdlPresentation(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MdlPresentationSuccess")
    deepHashMdlPresentation(value: message, hasher: &hasher)
  }
}

/// Operation failed
///
/// Generated class from Pigeon that represents data sent in messages.
struct MdlPresentationError: MdlPresentationResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MdlPresentationError? {
    let message = pigeonVar_list[0] as! String

    return MdlPresentationError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: MdlPresentationError, rhs: MdlPresentationError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMdlPresentation(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MdlPresentationError")
    deepHashMdlPresentation(value: message, hasher: &hasher)
  }
}

private class MdlPresentationPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MdlPresentationState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MdlNfcPhase(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MdlNamespaceItem.fromList(self.readValue() as! [Any?])
    case 132:
      return MdlNamespaceRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return MdlItemsRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return MdlPresentationStateUpdate.fromList(self.readValue() as! [Any?])
    case 135:
      return MdlPresentationSuccess.fromList(self.readValue() as! [Any?])
    case 136:
      return MdlPresentationError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MdlPresentationPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MdlPresentationState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MdlNfcPhase {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MdlNamespaceItem {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MdlNamespaceRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MdlItemsRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MdlPresentationStateUpdate {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? MdlPresentationSuccess {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? MdlPresentationError {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MdlPresentationPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MdlPresentationPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MdlPresentationPigeonCodecWriter(data: data)
  }
}

class MdlPresentationPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MdlPresentationPigeonCodec(readerWriter: MdlPresentationPigeonCodecReaderWriter())
}


/// Callback interface for presentation state updates
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MdlPresentationCallbackProtocol {
  /// Called when the presentation state changes
  func onStateChange(update updateArg: MdlPresentationStateUpdate, completion: @escaping (Result<Void, MdlPresentationPigeonError>) -> Void)
}
class MdlPresentationCallback: MdlPresentationCallbackProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MdlPresentationPigeonCodec {
    return MdlPresentationPigeonCodec.shared
  }
  /// Called when the presentation state changes
  func onStateChange(update updateArg: MdlPresentationStateUpdate, completion: @escaping (Result<Void, MdlPresentationPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.sprucekit_mobile.MdlPresentationCallback.onStateChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(MdlPresentationPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// ISO 18013-5 mDL Presentation API
///
/// Handles close proximity presentation of mDL credentials via BLE
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MdlPresentation {
  /// Initialize a QR code based presentation session
  ///
  /// @param packId The credential pack ID containing the mDL
  /// @param credentialId The credential ID of the mDL to present
  /// @return Result indicating success or error
  func initializeQrPresentation(packId: String, credentialId: String, completion: @escaping (Result<MdlPresentationResult, Error>) -> Void)
  /// Whether this device can present over an NFC tap
  ///
  /// True when the device has an NFC adapter that is turned on and
  /// supports host card emulation. Always false on iOS.
  func isNfcPresentationAvailable() throws -> Bool
  /// Arm an NFC tap based presentation session
  ///
  /// The BLE session starts when a reader taps the phone. The engagement
  /// uses ISO 18013-5 static handover with BLE central client mode. State
  /// updates arrive on [MdlPresentationCallback.onStateChange].
  ///
  /// @param packId The credential pack ID containing the mDL
  /// @param credentialId The credential ID of the mDL to present
  /// @return Result indicating success or error
  func initializeNfcPresentation(packId: String, credentialId: String, completion: @escaping (Result<MdlPresentationResult, Error>) -> Void)
  /// Get the current QR code URI for the presentation
  ///
  /// @return The QR code URI, or null if not in the correct state
  func getQrCodeUri() throws -> String?
  /// Get the current presentation state
  ///
  /// @return Current state update with all relevant data
  func getCurrentState() throws -> MdlPresentationStateUpdate
  /// Submit the user's selection of namespaces/fields to share
  ///
  /// The map structure is: docType -> namespace -> list of field names
  ///
  /// @param selectedNamespaces The selected namespaces and fields
  /// @return Result indicating success or error
  func submitNamespaces(selectedNamespaces: [String: [String: [String]]], completion: @escaping (Result<MdlPresentationResult, Error>) -> Void)
  /// Cancel the current presentation session
  func cancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MdlPresentationSetup {
  static var codec: FlutterStandardMessageCodec { MdlPresentationPigeonCodec.shared }
  /// Sets up an instance of `MdlPresentation` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MdlPresentation?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialize a QR code based presentation session
    ///
    /// @param packId The credential pack ID containing the mDL
    /// @param credentialId The credential ID of the mDL to present
    /// @return Result indicating success or error
    let initializeQrPresentationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.initializeQrPresentation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeQrPresentationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let packIdArg = args[0] as! String
        let credentialIdArg = args[1] as! String
        api.initializeQrPresentation(packId: packIdArg, credentialId: credentialIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeQrPresentationChannel.setMessageHandler(nil)
    }
    /// Whether this device can present over an NFC tap
    ///
    /// True when the device has an NFC adapter that is turned on and
    /// supports host card emulation. Always false on iOS.
    let isNfcPresentationAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.isNfcPresentationAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isNfcPresentationAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isNfcPresentationAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isNfcPresentationAvailableChannel.setMessageHandler(nil)
    }
    /// Arm an NFC tap based presentation session
    ///
    /// The BLE session starts when a reader taps the phone. The engagement
    /// uses ISO 18013-5 static handover with BLE central client mode. State
    /// updates arrive on [MdlPresentationCallback.onStateChange].
    ///
    /// @param packId The credential pack ID containing the mDL
    /// @param credentialId The credential ID of the mDL to present
    /// @return Result indicating success or error
    let initializeNfcPresentationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.initializeNfcPresentation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeNfcPresentationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let packIdArg = args[0] as! String
        let credentialIdArg = args[1] as! String
        api.initializeNfcPresentation(packId: packIdArg, credentialId: credentialIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeNfcPresentationChannel.setMessageHandler(nil)
    }
    /// Get the current QR code URI for the presentation
    ///
    /// @return The QR code URI, or null if not in the correct state
    let getQrCodeUriChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.getQrCodeUri\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getQrCodeUriChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getQrCodeUri()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getQrCodeUriChannel.setMessageHandler(nil)
    }
    /// Get the current presentation state
    ///
    /// @return Current state update with all relevant data
    let getCurrentStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.getCurrentState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentStateChannel.setMessageHandler(nil)
    }
    /// Submit the user's selection of namespaces/fields to share
    ///
    /// The map structure is: docType -> namespace -> list of field names
    ///
    /// @param selectedNamespaces The selected namespaces and fields
    /// @return Result indicating success or error
    let submitNamespacesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.submitNamespaces\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitNamespacesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let selectedNamespacesArg = args[0] as! [String: [String: [String]]]
        api.submitNamespaces(selectedNamespaces: selectedNamespacesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitNamespacesChannel.setMessageHandler(nil)
    }
    /// Cancel the current presentation session
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.MdlPresentation.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
