// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class Oid4vpPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "Oid4vpPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? Oid4vpPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsOid4vp(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashOid4vp(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsOid4vp(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsOid4vp(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsOid4vp(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsOid4vp(lhsKey, rhsKey) {
          if deepEqualsOid4vp(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsOid4vp(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashOid4vp(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashOid4vp(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashOid4vp(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashOid4vp(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashOid4vp(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashOid4vp(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Selects which OID4VP protocol version the holder negotiates for a request.
///
/// - [auto] inspects the request and picks the matching version (recommended).
/// - [v1] forces OID4VP 1.0 (final).
/// - [draft18] forces OID4VP Draft 18.
/// - [draft13] forces OID4VP Draft 13 (served by translating onto the Draft 18
///   engine). `auto` detects draft 13 only when the link carries
///   `response_mode=post`; for draft-13 requests delivered purely by
///   `request_uri`, force this mode.
enum Oid4vpCompatibilityMode: Int {
  case auto = 0
  case v1 = 1
  case draft18 = 2
  case draft13 = 3
}

/// Options for creating the permission response
///
/// Generated class from Pigeon that represents data sent in messages.
struct ResponseOptions: Hashable {
  var forceArraySerialization: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ResponseOptions? {
    let forceArraySerialization = pigeonVar_list[0] as! Bool

    return ResponseOptions(
      forceArraySerialization: forceArraySerialization
    )
  }
  func toList() -> [Any?] {
    return [
      forceArraySerialization
    ]
  }
  static func == (lhs: ResponseOptions, rhs: ResponseOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.forceArraySerialization, rhs.forceArraySerialization)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ResponseOptions")
    deepHashOid4vp(value: forceArraySerialization, hasher: &hasher)
  }
}

/// A field requested by the verifier
///
/// Generated class from Pigeon that represents data sent in messages.
struct RequestedFieldData: Hashable {
  var id: String
  var name: String? = nil
  var path: String
  var required: Bool
  var retained: Bool
  var purpose: String? = nil
  var credentialQueryId: String
  var rawFields: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RequestedFieldData? {
    let id = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let path = pigeonVar_list[2] as! String
    let required = pigeonVar_list[3] as! Bool
    let retained = pigeonVar_list[4] as! Bool
    let purpose: String? = nilOrValue(pigeonVar_list[5])
    let credentialQueryId = pigeonVar_list[6] as! String
    let rawFields = pigeonVar_list[7] as! [String]

    return RequestedFieldData(
      id: id,
      name: name,
      path: path,
      required: required,
      retained: retained,
      purpose: purpose,
      credentialQueryId: credentialQueryId,
      rawFields: rawFields
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      path,
      required,
      retained,
      purpose,
      credentialQueryId,
      rawFields,
    ]
  }
  static func == (lhs: RequestedFieldData, rhs: RequestedFieldData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.id, rhs.id) && deepEqualsOid4vp(lhs.name, rhs.name) && deepEqualsOid4vp(lhs.path, rhs.path) && deepEqualsOid4vp(lhs.required, rhs.required) && deepEqualsOid4vp(lhs.retained, rhs.retained) && deepEqualsOid4vp(lhs.purpose, rhs.purpose) && deepEqualsOid4vp(lhs.credentialQueryId, rhs.credentialQueryId) && deepEqualsOid4vp(lhs.rawFields, rhs.rawFields)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RequestedFieldData")
    deepHashOid4vp(value: id, hasher: &hasher)
    deepHashOid4vp(value: name, hasher: &hasher)
    deepHashOid4vp(value: path, hasher: &hasher)
    deepHashOid4vp(value: required, hasher: &hasher)
    deepHashOid4vp(value: retained, hasher: &hasher)
    deepHashOid4vp(value: purpose, hasher: &hasher)
    deepHashOid4vp(value: credentialQueryId, hasher: &hasher)
    deepHashOid4vp(value: rawFields, hasher: &hasher)
  }
}

/// Stable identifier for a presentable credential within a single
/// `handleAuthorizationRequest` session.
///
/// A credential is uniquely identified by the pair
/// `(credentialId, credentialQueryId)`: the same credential may appear
/// once per DCQL credential query that it satisfies. Use this key
/// (not list position) when calling `getRequestedFields` and `submitResponse`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PresentableCredentialKey: Hashable {
  var credentialId: String
  var credentialQueryId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PresentableCredentialKey? {
    let credentialId = pigeonVar_list[0] as! String
    let credentialQueryId = pigeonVar_list[1] as! String

    return PresentableCredentialKey(
      credentialId: credentialId,
      credentialQueryId: credentialQueryId
    )
  }
  func toList() -> [Any?] {
    return [
      credentialId,
      credentialQueryId,
    ]
  }
  static func == (lhs: PresentableCredentialKey, rhs: PresentableCredentialKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.credentialId, rhs.credentialId) && deepEqualsOid4vp(lhs.credentialQueryId, rhs.credentialQueryId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PresentableCredentialKey")
    deepHashOid4vp(value: credentialId, hasher: &hasher)
    deepHashOid4vp(value: credentialQueryId, hasher: &hasher)
  }
}

/// A credential that can be presented.
///
/// `credentialId` and `credentialQueryId` together form the stable key
/// used to refer back to this credential in subsequent calls
/// (`getRequestedFields`, `submitResponse`). See `PresentableCredentialKey`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PresentableCredentialData: Hashable {
  var credentialId: String
  var credentialQueryId: String
  var selectiveDisclosable: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PresentableCredentialData? {
    let credentialId = pigeonVar_list[0] as! String
    let credentialQueryId = pigeonVar_list[1] as! String
    let selectiveDisclosable = pigeonVar_list[2] as! Bool

    return PresentableCredentialData(
      credentialId: credentialId,
      credentialQueryId: credentialQueryId,
      selectiveDisclosable: selectiveDisclosable
    )
  }
  func toList() -> [Any?] {
    return [
      credentialId,
      credentialQueryId,
      selectiveDisclosable,
    ]
  }
  static func == (lhs: PresentableCredentialData, rhs: PresentableCredentialData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.credentialId, rhs.credentialId) && deepEqualsOid4vp(lhs.credentialQueryId, rhs.credentialQueryId) && deepEqualsOid4vp(lhs.selectiveDisclosable, rhs.selectiveDisclosable)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PresentableCredentialData")
    deepHashOid4vp(value: credentialId, hasher: &hasher)
    deepHashOid4vp(value: credentialQueryId, hasher: &hasher)
    deepHashOid4vp(value: selectiveDisclosable, hasher: &hasher)
  }
}

/// Information about the permission request
///
/// Generated class from Pigeon that represents data sent in messages.
struct PermissionRequestInfo: Hashable {
  var clientId: String? = nil
  var domain: String? = nil
  var purpose: String? = nil
  var isMultiCredentialSelection: Bool
  var isMultiCredentialMatching: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionRequestInfo? {
    let clientId: String? = nilOrValue(pigeonVar_list[0])
    let domain: String? = nilOrValue(pigeonVar_list[1])
    let purpose: String? = nilOrValue(pigeonVar_list[2])
    let isMultiCredentialSelection = pigeonVar_list[3] as! Bool
    let isMultiCredentialMatching = pigeonVar_list[4] as! Bool

    return PermissionRequestInfo(
      clientId: clientId,
      domain: domain,
      purpose: purpose,
      isMultiCredentialSelection: isMultiCredentialSelection,
      isMultiCredentialMatching: isMultiCredentialMatching
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      domain,
      purpose,
      isMultiCredentialSelection,
      isMultiCredentialMatching,
    ]
  }
  static func == (lhs: PermissionRequestInfo, rhs: PermissionRequestInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.clientId, rhs.clientId) && deepEqualsOid4vp(lhs.domain, rhs.domain) && deepEqualsOid4vp(lhs.purpose, rhs.purpose) && deepEqualsOid4vp(lhs.isMultiCredentialSelection, rhs.isMultiCredentialSelection) && deepEqualsOid4vp(lhs.isMultiCredentialMatching, rhs.isMultiCredentialMatching)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PermissionRequestInfo")
    deepHashOid4vp(value: clientId, hasher: &hasher)
    deepHashOid4vp(value: domain, hasher: &hasher)
    deepHashOid4vp(value: purpose, hasher: &hasher)
    deepHashOid4vp(value: isMultiCredentialSelection, hasher: &hasher)
    deepHashOid4vp(value: isMultiCredentialMatching, hasher: &hasher)
  }
}

/// Result of OID4VP operations
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol Oid4vpResult {

}

/// Operation succeeded
///
/// Generated class from Pigeon that represents data sent in messages.
struct Oid4vpSuccess: Oid4vpResult {
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Oid4vpSuccess? {
    let message: String? = nilOrValue(pigeonVar_list[0])

    return Oid4vpSuccess(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: Oid4vpSuccess, rhs: Oid4vpSuccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Oid4vpSuccess")
    deepHashOid4vp(value: message, hasher: &hasher)
  }
}

/// Operation failed with error
///
/// Generated class from Pigeon that represents data sent in messages.
struct Oid4vpError: Oid4vpResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Oid4vpError? {
    let message = pigeonVar_list[0] as! String

    return Oid4vpError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: Oid4vpError, rhs: Oid4vpError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Oid4vpError")
    deepHashOid4vp(value: message, hasher: &hasher)
  }
}

/// Result of handling an authorization request
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol HandleAuthRequestResult {

}

/// Authorization request handled successfully
///
/// Generated class from Pigeon that represents data sent in messages.
struct HandleAuthRequestSuccess: HandleAuthRequestResult {
  var credentials: [PresentableCredentialData]
  var info: PermissionRequestInfo


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HandleAuthRequestSuccess? {
    let credentials = pigeonVar_list[0] as! [PresentableCredentialData]
    let info = pigeonVar_list[1] as! PermissionRequestInfo

    return HandleAuthRequestSuccess(
      credentials: credentials,
      info: info
    )
  }
  func toList() -> [Any?] {
    return [
      credentials,
      info,
    ]
  }
  static func == (lhs: HandleAuthRequestSuccess, rhs: HandleAuthRequestSuccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.credentials, rhs.credentials) && deepEqualsOid4vp(lhs.info, rhs.info)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HandleAuthRequestSuccess")
    deepHashOid4vp(value: credentials, hasher: &hasher)
    deepHashOid4vp(value: info, hasher: &hasher)
  }
}

/// Authorization request failed
///
/// Generated class from Pigeon that represents data sent in messages.
struct HandleAuthRequestError: HandleAuthRequestResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HandleAuthRequestError? {
    let message = pigeonVar_list[0] as! String

    return HandleAuthRequestError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: HandleAuthRequestError, rhs: HandleAuthRequestError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HandleAuthRequestError")
    deepHashOid4vp(value: message, hasher: &hasher)
  }
}

/// A group of credentials matching a credential query
///
/// Generated class from Pigeon that represents data sent in messages.
struct CredentialQueryGroupData: Hashable {
  var credentialQueryId: String
  var credentials: [PresentableCredentialData]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CredentialQueryGroupData? {
    let credentialQueryId = pigeonVar_list[0] as! String
    let credentials = pigeonVar_list[1] as! [PresentableCredentialData]

    return CredentialQueryGroupData(
      credentialQueryId: credentialQueryId,
      credentials: credentials
    )
  }
  func toList() -> [Any?] {
    return [
      credentialQueryId,
      credentials,
    ]
  }
  static func == (lhs: CredentialQueryGroupData, rhs: CredentialQueryGroupData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.credentialQueryId, rhs.credentialQueryId) && deepEqualsOid4vp(lhs.credentials, rhs.credentials)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CredentialQueryGroupData")
    deepHashOid4vp(value: credentialQueryId, hasher: &hasher)
    deepHashOid4vp(value: credentials, hasher: &hasher)
  }
}

/// A credential requirement from the verifier
///
/// Generated class from Pigeon that represents data sent in messages.
struct CredentialRequirementData: Hashable {
  var displayName: String
  var required: Bool
  var credentialQueryIds: [String]
  var credentials: [PresentableCredentialData]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CredentialRequirementData? {
    let displayName = pigeonVar_list[0] as! String
    let required = pigeonVar_list[1] as! Bool
    let credentialQueryIds = pigeonVar_list[2] as! [String]
    let credentials = pigeonVar_list[3] as! [PresentableCredentialData]

    return CredentialRequirementData(
      displayName: displayName,
      required: required,
      credentialQueryIds: credentialQueryIds,
      credentials: credentials
    )
  }
  func toList() -> [Any?] {
    return [
      displayName,
      required,
      credentialQueryIds,
      credentials,
    ]
  }
  static func == (lhs: CredentialRequirementData, rhs: CredentialRequirementData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOid4vp(lhs.displayName, rhs.displayName) && deepEqualsOid4vp(lhs.required, rhs.required) && deepEqualsOid4vp(lhs.credentialQueryIds, rhs.credentialQueryIds) && deepEqualsOid4vp(lhs.credentials, rhs.credentials)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CredentialRequirementData")
    deepHashOid4vp(value: displayName, hasher: &hasher)
    deepHashOid4vp(value: required, hasher: &hasher)
    deepHashOid4vp(value: credentialQueryIds, hasher: &hasher)
    deepHashOid4vp(value: credentials, hasher: &hasher)
  }
}

private class Oid4vpPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return Oid4vpCompatibilityMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ResponseOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return RequestedFieldData.fromList(self.readValue() as! [Any?])
    case 132:
      return PresentableCredentialKey.fromList(self.readValue() as! [Any?])
    case 133:
      return PresentableCredentialData.fromList(self.readValue() as! [Any?])
    case 134:
      return PermissionRequestInfo.fromList(self.readValue() as! [Any?])
    case 135:
      return Oid4vpSuccess.fromList(self.readValue() as! [Any?])
    case 136:
      return Oid4vpError.fromList(self.readValue() as! [Any?])
    case 137:
      return HandleAuthRequestSuccess.fromList(self.readValue() as! [Any?])
    case 138:
      return HandleAuthRequestError.fromList(self.readValue() as! [Any?])
    case 139:
      return CredentialQueryGroupData.fromList(self.readValue() as! [Any?])
    case 140:
      return CredentialRequirementData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class Oid4vpPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Oid4vpCompatibilityMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ResponseOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RequestedFieldData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PresentableCredentialKey {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PresentableCredentialData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PermissionRequestInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? Oid4vpSuccess {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? Oid4vpError {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? HandleAuthRequestSuccess {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? HandleAuthRequestError {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? CredentialQueryGroupData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? CredentialRequirementData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class Oid4vpPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return Oid4vpPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return Oid4vpPigeonCodecWriter(data: data)
  }
}

class Oid4vpPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = Oid4vpPigeonCodec(readerWriter: Oid4vpPigeonCodecReaderWriter())
}


/// OID4VP credential presentation API
///
/// Handles the OpenID for Verifiable Presentation flow
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Oid4vp {
  /// Create a holder with credentials for presentation
  ///
  /// @param credentialPackIds List of credential pack IDs to use
  /// @param trustedDids List of trusted DIDs for verification
  /// @param keyId The key identifier for signing (will create if doesn't exist)
  /// @param contextMap Optional JSON-LD context map
  func createHolder(credentialPackIds: [String], trustedDids: [String], keyId: String, contextMap: [String: String]?, completion: @escaping (Result<Oid4vpResult, Error>) -> Void)
  /// Handle an authorization request URL
  ///
  /// @param url The authorization request URL (e.g., "openid4vp://...")
  /// @param mode Which OID4VP version to negotiate. Use
  ///   [Oid4vpCompatibilityMode.auto] to detect it from the request.
  /// @return HandleAuthRequestResult with matching credentials on success
  func handleAuthorizationRequest(url: String, mode: Oid4vpCompatibilityMode, completion: @escaping (Result<HandleAuthRequestResult, Error>) -> Void)
  /// Get requested fields for a credential
  ///
  /// @param key Stable key identifying the credential. Take the
  ///   `credentialId` and `credentialQueryId` from a `PresentableCredentialData`
  ///   returned by `handleAuthorizationRequest`, `getCredentialRequirements`,
  ///   or `getCredentialsGroupedByQuery`.
  /// @return List of requested fields for the credential
  func getRequestedFields(key: PresentableCredentialKey) throws -> [RequestedFieldData]
  /// Submit the presentation response
  ///
  /// @param selectedCredentials Stable keys of the credentials the user selected
  /// @param selectedFieldPaths List of selected field paths per credential, in
  ///   the same order as `selectedCredentials`
  /// @param options Response configuration options
  func submitResponse(selectedCredentials: [PresentableCredentialKey], selectedFieldPaths: [[String]], options: ResponseOptions, completion: @escaping (Result<Oid4vpResult, Error>) -> Void)
  /// Get credential requirements from the permission request
  ///
  /// @return List of credential requirements
  func getCredentialRequirements() throws -> [CredentialRequirementData]
  /// Get credentials grouped by credential query
  ///
  /// @return List of credential query groups
  func getCredentialsGroupedByQuery() throws -> [CredentialQueryGroupData]
  /// Get credential query IDs from the permission request
  ///
  /// @return List of credential query ID strings
  func getCredentialQueryIds() throws -> [String]
  /// Cancel and cleanup the current session
  func cancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class Oid4vpSetup {
  static var codec: FlutterStandardMessageCodec { Oid4vpPigeonCodec.shared }
  /// Sets up an instance of `Oid4vp` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Oid4vp?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Create a holder with credentials for presentation
    ///
    /// @param credentialPackIds List of credential pack IDs to use
    /// @param trustedDids List of trusted DIDs for verification
    /// @param keyId The key identifier for signing (will create if doesn't exist)
    /// @param contextMap Optional JSON-LD context map
    let createHolderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.createHolder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createHolderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialPackIdsArg = args[0] as! [String]
        let trustedDidsArg = args[1] as! [String]
        let keyIdArg = args[2] as! String
        let contextMapArg: [String: String]? = nilOrValue(args[3])
        api.createHolder(credentialPackIds: credentialPackIdsArg, trustedDids: trustedDidsArg, keyId: keyIdArg, contextMap: contextMapArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createHolderChannel.setMessageHandler(nil)
    }
    /// Handle an authorization request URL
    ///
    /// @param url The authorization request URL (e.g., "openid4vp://...")
    /// @param mode Which OID4VP version to negotiate. Use
    ///   [Oid4vpCompatibilityMode.auto] to detect it from the request.
    /// @return HandleAuthRequestResult with matching credentials on success
    let handleAuthorizationRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.handleAuthorizationRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleAuthorizationRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let modeArg = args[1] as! Oid4vpCompatibilityMode
        api.handleAuthorizationRequest(url: urlArg, mode: modeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handleAuthorizationRequestChannel.setMessageHandler(nil)
    }
    /// Get requested fields for a credential
    ///
    /// @param key Stable key identifying the credential. Take the
    ///   `credentialId` and `credentialQueryId` from a `PresentableCredentialData`
    ///   returned by `handleAuthorizationRequest`, `getCredentialRequirements`,
    ///   or `getCredentialsGroupedByQuery`.
    /// @return List of requested fields for the credential
    let getRequestedFieldsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.getRequestedFields\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRequestedFieldsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! PresentableCredentialKey
        do {
          let result = try api.getRequestedFields(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getRequestedFieldsChannel.setMessageHandler(nil)
    }
    /// Submit the presentation response
    ///
    /// @param selectedCredentials Stable keys of the credentials the user selected
    /// @param selectedFieldPaths List of selected field paths per credential, in
    ///   the same order as `selectedCredentials`
    /// @param options Response configuration options
    let submitResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.submitResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let selectedCredentialsArg = args[0] as! [PresentableCredentialKey]
        let selectedFieldPathsArg = args[1] as! [[String]]
        let optionsArg = args[2] as! ResponseOptions
        api.submitResponse(selectedCredentials: selectedCredentialsArg, selectedFieldPaths: selectedFieldPathsArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitResponseChannel.setMessageHandler(nil)
    }
    /// Get credential requirements from the permission request
    ///
    /// @return List of credential requirements
    let getCredentialRequirementsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.getCredentialRequirements\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialRequirementsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCredentialRequirements()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCredentialRequirementsChannel.setMessageHandler(nil)
    }
    /// Get credentials grouped by credential query
    ///
    /// @return List of credential query groups
    let getCredentialsGroupedByQueryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.getCredentialsGroupedByQuery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialsGroupedByQueryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCredentialsGroupedByQuery()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCredentialsGroupedByQueryChannel.setMessageHandler(nil)
    }
    /// Get credential query IDs from the permission request
    ///
    /// @return List of credential query ID strings
    let getCredentialQueryIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.getCredentialQueryIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialQueryIdsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCredentialQueryIds()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCredentialQueryIdsChannel.setMessageHandler(nil)
    }
    /// Cancel and cleanup the current session
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vp.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
