// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class Oid4vciPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "Oid4vciPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? Oid4vciPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsOid4vci(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsOid4vci(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsOid4vci(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashOid4vci(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashOid4vci(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashOid4vci(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// DID method for proof of possession
enum DidMethod: Int {
  case jwk = 0
  case key = 1
}

/// Options for credential exchange
///
/// Generated class from Pigeon that represents data sent in messages.
struct Oid4vciExchangeOptions: Hashable {
  /// Whether to verify the credential after exchange
  var verifyAfterExchange: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Oid4vciExchangeOptions? {
    let verifyAfterExchange = pigeonVar_list[0] as! Bool

    return Oid4vciExchangeOptions(
      verifyAfterExchange: verifyAfterExchange
    )
  }
  func toList() -> [Any?] {
    return [
      verifyAfterExchange
    ]
  }
  static func == (lhs: Oid4vciExchangeOptions, rhs: Oid4vciExchangeOptions) -> Bool {
    return deepEqualsOid4vci(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashOid4vci(value: toList(), hasher: &hasher)
  }
}

/// Credential received from issuance
///
/// Generated class from Pigeon that represents data sent in messages.
struct IssuedCredential: Hashable {
  /// The credential payload as string (JSON, JWT, etc.)
  var payload: String
  /// The credential format (e.g., "jwt_vc_json", "ldp_vc", "mso_mdoc")
  var format: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IssuedCredential? {
    let payload = pigeonVar_list[0] as! String
    let format = pigeonVar_list[1] as! String

    return IssuedCredential(
      payload: payload,
      format: format
    )
  }
  func toList() -> [Any?] {
    return [
      payload,
      format,
    ]
  }
  static func == (lhs: IssuedCredential, rhs: IssuedCredential) -> Bool {
    return deepEqualsOid4vci(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashOid4vci(value: toList(), hasher: &hasher)
  }
}

/// Result of OID4VCI issuance
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol Oid4vciResult {

}

/// Issuance succeeded with credentials
///
/// Generated class from Pigeon that represents data sent in messages.
struct Oid4vciSuccess: Oid4vciResult {
  var credentials: [IssuedCredential]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Oid4vciSuccess? {
    let credentials = pigeonVar_list[0] as! [IssuedCredential]

    return Oid4vciSuccess(
      credentials: credentials
    )
  }
  func toList() -> [Any?] {
    return [
      credentials
    ]
  }
  static func == (lhs: Oid4vciSuccess, rhs: Oid4vciSuccess) -> Bool {
    return deepEqualsOid4vci(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashOid4vci(value: toList(), hasher: &hasher)
  }
}

/// Issuance failed with error
///
/// Generated class from Pigeon that represents data sent in messages.
struct Oid4vciError: Oid4vciResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Oid4vciError? {
    let message = pigeonVar_list[0] as! String

    return Oid4vciError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: Oid4vciError, rhs: Oid4vciError) -> Bool {
    return deepEqualsOid4vci(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashOid4vci(value: toList(), hasher: &hasher)
  }
}

private class Oid4vciPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DidMethod(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return Oid4vciExchangeOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return IssuedCredential.fromList(self.readValue() as! [Any?])
    case 132:
      return Oid4vciSuccess.fromList(self.readValue() as! [Any?])
    case 133:
      return Oid4vciError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class Oid4vciPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DidMethod {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? Oid4vciExchangeOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? IssuedCredential {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Oid4vciSuccess {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? Oid4vciError {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class Oid4vciPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return Oid4vciPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return Oid4vciPigeonCodecWriter(data: data)
  }
}

class Oid4vciPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = Oid4vciPigeonCodec(readerWriter: Oid4vciPigeonCodecReaderWriter())
}


/// OID4VCI credential issuance API
///
/// Handles the OpenID for Verifiable Credential Issuance flow
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Oid4vci {
  /// Run the complete OID4VCI issuance flow
  ///
  /// This method handles:
  /// 1. Initiating session with the credential offer
  /// 2. Token exchange
  /// 3. Proof of possession generation
  /// 4. Credential exchange
  ///
  /// @param credentialOffer The full credential offer URL (e.g., "openid-credential-offer://...")
  /// @param clientId The client ID for the wallet
  /// @param redirectUrl The redirect URL for the wallet
  /// @param keyId The key identifier for signing (will create if doesn't exist)
  /// @param didMethod The DID method for proof of possession
  /// @param contextMap Optional JSON-LD context map for credential parsing
  /// @return Oid4vciResult with credentials on success or error message on failure
  func runIssuance(credentialOffer: String, clientId: String, redirectUrl: String, keyId: String, didMethod: DidMethod, contextMap: [String: String]?, completion: @escaping (Result<Oid4vciResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class Oid4vciSetup {
  static var codec: FlutterStandardMessageCodec { Oid4vciPigeonCodec.shared }
  /// Sets up an instance of `Oid4vci` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Oid4vci?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Run the complete OID4VCI issuance flow
    ///
    /// This method handles:
    /// 1. Initiating session with the credential offer
    /// 2. Token exchange
    /// 3. Proof of possession generation
    /// 4. Credential exchange
    ///
    /// @param credentialOffer The full credential offer URL (e.g., "openid-credential-offer://...")
    /// @param clientId The client ID for the wallet
    /// @param redirectUrl The redirect URL for the wallet
    /// @param keyId The key identifier for signing (will create if doesn't exist)
    /// @param didMethod The DID method for proof of possession
    /// @param contextMap Optional JSON-LD context map for credential parsing
    /// @return Oid4vciResult with credentials on success or error message on failure
    let runIssuanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Oid4vci.runIssuance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runIssuanceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialOfferArg = args[0] as! String
        let clientIdArg = args[1] as! String
        let redirectUrlArg = args[2] as! String
        let keyIdArg = args[3] as! String
        let didMethodArg = args[4] as! DidMethod
        let contextMapArg: [String: String]? = nilOrValue(args[5])
        api.runIssuance(credentialOffer: credentialOfferArg, clientId: clientIdArg, redirectUrl: redirectUrlArg, keyId: keyIdArg, didMethod: didMethodArg, contextMap: contextMapArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      runIssuanceChannel.setMessageHandler(nil)
    }
  }
}
