// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class SpruceUtilsPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "SpruceUtilsPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? SpruceUtilsPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsSpruceUtils(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashSpruceUtils(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsSpruceUtils(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsSpruceUtils(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsSpruceUtils(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsSpruceUtils(lhsKey, rhsKey) {
          if deepEqualsSpruceUtils(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsSpruceUtils(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashSpruceUtils(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashSpruceUtils(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashSpruceUtils(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashSpruceUtils(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashSpruceUtils(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashSpruceUtils(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// The type of a PDF supplement.
///
/// New supplement types can be added here without changing the function
/// signature of `generateCredentialPdf`.
enum PdfSupplementType: Int {
  case barcode = 0
}

/// Barcode type for PDF supplements
enum PdfBarcodeType: Int {
  case qrCode = 0
  case pdf417 = 1
}

/// Selective-disclosure mode for VP token generation.
///
/// Mirrors the Rust `DisclosureSelection` enum.  The `type` discriminator
/// keeps the Pigeon class extensible: future modes (path-based selection,
/// presentation-definition driven, etc.) can be added without changing
/// [generateCredentialVpToken]'s signature.
enum DisclosureSelectionType: Int {
  case hideOnly = 0
  case selectOnly = 1
}

/// Result of generating a mock mDL
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol GenerateMockMdlResult {

}

/// Mock mDL generated successfully - stored in a CredentialPack
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerateMockMdlSuccess: GenerateMockMdlResult {
  /// The credential pack ID where the mDL was stored
  var packId: String
  /// The credential ID of the generated mDL
  var credentialId: String
  /// The raw mSO mDoc as base64 string for storage
  var rawCredential: String
  /// The key alias used for signing
  var keyAlias: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerateMockMdlSuccess? {
    let packId = pigeonVar_list[0] as! String
    let credentialId = pigeonVar_list[1] as! String
    let rawCredential = pigeonVar_list[2] as! String
    let keyAlias = pigeonVar_list[3] as! String

    return GenerateMockMdlSuccess(
      packId: packId,
      credentialId: credentialId,
      rawCredential: rawCredential,
      keyAlias: keyAlias
    )
  }
  func toList() -> [Any?] {
    return [
      packId,
      credentialId,
      rawCredential,
      keyAlias,
    ]
  }
  static func == (lhs: GenerateMockMdlSuccess, rhs: GenerateMockMdlSuccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.packId, rhs.packId) && deepEqualsSpruceUtils(lhs.credentialId, rhs.credentialId) && deepEqualsSpruceUtils(lhs.rawCredential, rhs.rawCredential) && deepEqualsSpruceUtils(lhs.keyAlias, rhs.keyAlias)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerateMockMdlSuccess")
    deepHashSpruceUtils(value: packId, hasher: &hasher)
    deepHashSpruceUtils(value: credentialId, hasher: &hasher)
    deepHashSpruceUtils(value: rawCredential, hasher: &hasher)
    deepHashSpruceUtils(value: keyAlias, hasher: &hasher)
  }
}

/// Mock mDL generation failed
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerateMockMdlError: GenerateMockMdlResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerateMockMdlError? {
    let message = pigeonVar_list[0] as! String

    return GenerateMockMdlError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: GenerateMockMdlError, rhs: GenerateMockMdlError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerateMockMdlError")
    deepHashSpruceUtils(value: message, hasher: &hasher)
  }
}

/// A supplement to include in the generated PDF.
///
/// This is an extensible carrier: the `type` field determines which optional
/// fields are relevant.  Adding a new supplement kind only requires a new
/// [PdfSupplementType] value and new optional fields — the API signature
/// stays the same.
///
/// **Barcode** (`type == PdfSupplementType.barcode`):
///   - `data` — raw bytes to encode (e.g. VP Token, AAMVA payload)
///   - `barcodeType` — QR Code or PDF-417
///
/// Generated class from Pigeon that represents data sent in messages.
struct PdfSupplement: Hashable {
  var type: PdfSupplementType
  /// Raw bytes to encode as a barcode. Required when `type` is `barcode`.
  var data: FlutterStandardTypedData? = nil
  /// The barcode symbology. Required when `type` is `barcode`.
  var barcodeType: PdfBarcodeType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfSupplement? {
    let type = pigeonVar_list[0] as! PdfSupplementType
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let barcodeType: PdfBarcodeType? = nilOrValue(pigeonVar_list[2])

    return PdfSupplement(
      type: type,
      data: data,
      barcodeType: barcodeType
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      data,
      barcodeType,
    ]
  }
  static func == (lhs: PdfSupplement, rhs: PdfSupplement) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.type, rhs.type) && deepEqualsSpruceUtils(lhs.data, rhs.data) && deepEqualsSpruceUtils(lhs.barcodeType, rhs.barcodeType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfSupplement")
    deepHashSpruceUtils(value: type, hasher: &hasher)
    deepHashSpruceUtils(value: data, hasher: &hasher)
    deepHashSpruceUtils(value: barcodeType, hasher: &hasher)
  }
}

/// Parameters for selective-disclosure VP token generation.
///
/// `hideOnly` reveals every disclosable claim **except** [fields]; ergonomic
/// for the mDL PDF case where almost every claim is shown and only `portrait`
/// is hidden.
///
/// `selectOnly` reveals **only** [fields]; ergonomic for narrow disclosures
/// like age verification (`["age_over_21"]`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct DisclosureSelection: Hashable {
  var type: DisclosureSelectionType
  /// Field names (top-level under `credentialSubject.driversLicense`) to
  /// hide or select, depending on [type].
  var fields: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisclosureSelection? {
    let type = pigeonVar_list[0] as! DisclosureSelectionType
    let fields = pigeonVar_list[1] as! [String]

    return DisclosureSelection(
      type: type,
      fields: fields
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      fields,
    ]
  }
  static func == (lhs: DisclosureSelection, rhs: DisclosureSelection) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.type, rhs.type) && deepEqualsSpruceUtils(lhs.fields, rhs.fields)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DisclosureSelection")
    deepHashSpruceUtils(value: type, hasher: &hasher)
    deepHashSpruceUtils(value: fields, hasher: &hasher)
  }
}

/// Parameters for [SpruceUtils.generateCredentialVpToken].
///
/// `audience` and `nonce` are reserved for a future KB-JWT signing path; the
/// current implementation does not produce a key-binding JWT (suitable for
/// offline PDF-embedded VPs).
///
/// Generated class from Pigeon that represents data sent in messages.
struct VpTokenParams: Hashable {
  var disclosure: DisclosureSelection
  var audience: String
  var nonce: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VpTokenParams? {
    let disclosure = pigeonVar_list[0] as! DisclosureSelection
    let audience = pigeonVar_list[1] as! String
    let nonce: String? = nilOrValue(pigeonVar_list[2])

    return VpTokenParams(
      disclosure: disclosure,
      audience: audience,
      nonce: nonce
    )
  }
  func toList() -> [Any?] {
    return [
      disclosure,
      audience,
      nonce,
    ]
  }
  static func == (lhs: VpTokenParams, rhs: VpTokenParams) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.disclosure, rhs.disclosure) && deepEqualsSpruceUtils(lhs.audience, rhs.audience) && deepEqualsSpruceUtils(lhs.nonce, rhs.nonce)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VpTokenParams")
    deepHashSpruceUtils(value: disclosure, hasher: &hasher)
    deepHashSpruceUtils(value: audience, hasher: &hasher)
    deepHashSpruceUtils(value: nonce, hasher: &hasher)
  }
}

private class SpruceUtilsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PdfSupplementType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PdfBarcodeType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DisclosureSelectionType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return GenerateMockMdlSuccess.fromList(self.readValue() as! [Any?])
    case 133:
      return GenerateMockMdlError.fromList(self.readValue() as! [Any?])
    case 134:
      return PdfSupplement.fromList(self.readValue() as! [Any?])
    case 135:
      return DisclosureSelection.fromList(self.readValue() as! [Any?])
    case 136:
      return VpTokenParams.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SpruceUtilsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PdfSupplementType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PdfBarcodeType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? DisclosureSelectionType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? GenerateMockMdlSuccess {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GenerateMockMdlError {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PdfSupplement {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? DisclosureSelection {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VpTokenParams {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SpruceUtilsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SpruceUtilsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SpruceUtilsPigeonCodecWriter(data: data)
  }
}

class SpruceUtilsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SpruceUtilsPigeonCodec(readerWriter: SpruceUtilsPigeonCodecReaderWriter())
}


/// Utility functions for credential operations
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SpruceUtils {
  /// Generate a mock mDL for testing
  ///
  /// Creates a self-signed test mDL credential and stores it in a new
  /// CredentialPack. The returned packId and credentialId can be used with
  /// MdlPresentation.initializeQrPresentation().
  ///
  /// @param keyAlias Optional key alias to use (defaults to "testMdl")
  /// @return Result with packId, credentialId, rawCredential, and keyAlias, or error
  func generateMockMdl(keyAlias: String?, completion: @escaping (Result<GenerateMockMdlResult, Error>) -> Void)
  /// Generate a PDF from a raw mDL credential.
  ///
  /// Accepts the raw mSO mDoc as a base64url-encoded IssuerSigned string
  /// (the same format returned by generateMockMdl's rawCredential field).
  ///
  /// @param rawMdoc Base64url-encoded IssuerSigned bytes of the mDL
  /// @param supplements Optional list of supplements to include in the PDF
  /// @return Raw PDF bytes ready to write to a file and share
  func generateCredentialPdf(rawMdoc: String, supplements: [PdfSupplement], completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Generate a compact SD-JWT VP token suitable for embedding in a PDF QR
  /// code.
  ///
  /// Wallets typically pass the returned bytes to [generateCredentialPdf] as
  /// a [PdfSupplement] with `barcodeType == PdfBarcodeType.qrCode`.
  ///
  /// **Currently only VCDM2 SD-JWT credentials are supported** (mDoc / JWT VC
  /// will throw `UnsupportedCredentialType`).  For the offline PDF case the
  /// returned token does **not** include a key-binding JWT — `audience` and
  /// `nonce` are accepted but not yet used.
  ///
  /// @param rawSdJwt Compact SD-JWT serialization of a VCDM2 SD-JWT credential
  /// @param params Disclosure selection + reserved audience / nonce
  /// @return Compact SD-JWT VP token bytes (UTF-8)
  func generateCredentialVpToken(rawSdJwt: String, params: VpTokenParams, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Generate a **QR-ready compressed** SD-JWT VP token.
  ///
  /// Combines [generateCredentialVpToken] with the Colorado-pattern compression
  /// pipeline (`deflate → BigUint → base10 → "9"-prefix`) used to fit dense
  /// VP tokens into a QR numeric-mode payload.
  ///
  /// This is the **recommended path** for embedding a VP token in a PDF QR:
  /// wallets pass the returned bytes directly to [generateCredentialPdf] as
  /// a [PdfSupplement] with `barcodeType == PdfBarcodeType.qrCode` — no
  /// manual compression step needed.
  ///
  /// The verifier side (a) auto-detects the leading `"9"` and decompresses
  /// transparently inside `verifySdJwtVp`, or (b) can call
  /// [decompressVpFromQr] directly for inspection.
  ///
  /// @param rawSdJwt Compact SD-JWT serialization of a VCDM2 SD-JWT credential
  /// @param params Disclosure selection + reserved audience / nonce
  /// @return QR-ready compressed bytes (UTF-8 ASCII, `"9"` prefix + base10 digits)
  func generateCompressedVpToken(rawSdJwt: String, params: VpTokenParams, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Generate a test mDL VCDM2 SD-JWT credential, returned as a compact
  /// SD-JWS string.
  ///
  /// The credential mirrors the schema CA DMV will issue once the SD-JWT
  /// microservice ships, but is signed with a test key generated on demand —
  /// so the credential is **not** verifiable against any production trust
  /// anchor. Useful for showcase / demo flows that need a real SD-JWT to
  /// drive [generateCompressedVpToken] without depending on a live issuer.
  ///
  /// @return Compact SD-JWT serialization (`<jwt>~<disc1>~…`) — feed straight
  ///         to [generateCredentialVpToken] / [generateCompressedVpToken]
  ///         as `rawSdJwt`.
  func generateTestMdlSdJwtCompact(completion: @escaping (Result<String, Error>) -> Void)
  /// Verify a compact SD-JWT VP token.
  ///
  /// Accepts either a raw compact SD-JWT (`<jwt>~<disc1>~…`) or a
  /// `"9"`-prefixed base10 QR payload — the implementation auto-detects the
  /// leading `"9"` and decompresses transparently before verifying. Throws
  /// on any failure (issuer signature mismatch, decompression error,
  /// disclosure hash mismatch, etc.); returns normally on success.
  ///
  /// Issuer trust is established via DID resolution (`AnyDidMethod`), so
  /// `did:jwk` issuers are fully verifiable offline.
  ///
  /// @param input Compact SD-JWT VP, or its `"9"`-prefixed compressed form
  ///              (e.g. straight from a [SpruceScanner] callback)
  func verifySdJwtVp(input: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Decompress a `"9"`-prefixed base10 QR payload back into a compact
  /// SD-JWT VP token.
  ///
  /// The inverse of the compression step inside [generateCompressedVpToken].
  /// Verification code typically does **not** need to call this directly —
  /// `verifySdJwtVp` auto-detects the prefix and decompresses internally —
  /// but it is exposed for inspection, logging, or non-verification flows
  /// (e.g. extracting fields client-side from a scanned QR).
  ///
  /// @param qrPayload Bytes scanned from the QR (`"9"` prefix + base10 digits)
  /// @return Original compact SD-JWT VP token bytes (UTF-8)
  func decompressVpFromQr(qrPayload: FlutterStandardTypedData, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SpruceUtilsSetup {
  static var codec: FlutterStandardMessageCodec { SpruceUtilsPigeonCodec.shared }
  /// Sets up an instance of `SpruceUtils` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SpruceUtils?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generate a mock mDL for testing
    ///
    /// Creates a self-signed test mDL credential and stores it in a new
    /// CredentialPack. The returned packId and credentialId can be used with
    /// MdlPresentation.initializeQrPresentation().
    ///
    /// @param keyAlias Optional key alias to use (defaults to "testMdl")
    /// @return Result with packId, credentialId, rawCredential, and keyAlias, or error
    let generateMockMdlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateMockMdl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateMockMdlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg: String? = nilOrValue(args[0])
        api.generateMockMdl(keyAlias: keyAliasArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateMockMdlChannel.setMessageHandler(nil)
    }
    /// Generate a PDF from a raw mDL credential.
    ///
    /// Accepts the raw mSO mDoc as a base64url-encoded IssuerSigned string
    /// (the same format returned by generateMockMdl's rawCredential field).
    ///
    /// @param rawMdoc Base64url-encoded IssuerSigned bytes of the mDL
    /// @param supplements Optional list of supplements to include in the PDF
    /// @return Raw PDF bytes ready to write to a file and share
    let generateCredentialPdfChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateCredentialPdf\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateCredentialPdfChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rawMdocArg = args[0] as! String
        let supplementsArg = args[1] as! [PdfSupplement]
        api.generateCredentialPdf(rawMdoc: rawMdocArg, supplements: supplementsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateCredentialPdfChannel.setMessageHandler(nil)
    }
    /// Generate a compact SD-JWT VP token suitable for embedding in a PDF QR
    /// code.
    ///
    /// Wallets typically pass the returned bytes to [generateCredentialPdf] as
    /// a [PdfSupplement] with `barcodeType == PdfBarcodeType.qrCode`.
    ///
    /// **Currently only VCDM2 SD-JWT credentials are supported** (mDoc / JWT VC
    /// will throw `UnsupportedCredentialType`).  For the offline PDF case the
    /// returned token does **not** include a key-binding JWT — `audience` and
    /// `nonce` are accepted but not yet used.
    ///
    /// @param rawSdJwt Compact SD-JWT serialization of a VCDM2 SD-JWT credential
    /// @param params Disclosure selection + reserved audience / nonce
    /// @return Compact SD-JWT VP token bytes (UTF-8)
    let generateCredentialVpTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateCredentialVpToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateCredentialVpTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rawSdJwtArg = args[0] as! String
        let paramsArg = args[1] as! VpTokenParams
        api.generateCredentialVpToken(rawSdJwt: rawSdJwtArg, params: paramsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateCredentialVpTokenChannel.setMessageHandler(nil)
    }
    /// Generate a **QR-ready compressed** SD-JWT VP token.
    ///
    /// Combines [generateCredentialVpToken] with the Colorado-pattern compression
    /// pipeline (`deflate → BigUint → base10 → "9"-prefix`) used to fit dense
    /// VP tokens into a QR numeric-mode payload.
    ///
    /// This is the **recommended path** for embedding a VP token in a PDF QR:
    /// wallets pass the returned bytes directly to [generateCredentialPdf] as
    /// a [PdfSupplement] with `barcodeType == PdfBarcodeType.qrCode` — no
    /// manual compression step needed.
    ///
    /// The verifier side (a) auto-detects the leading `"9"` and decompresses
    /// transparently inside `verifySdJwtVp`, or (b) can call
    /// [decompressVpFromQr] directly for inspection.
    ///
    /// @param rawSdJwt Compact SD-JWT serialization of a VCDM2 SD-JWT credential
    /// @param params Disclosure selection + reserved audience / nonce
    /// @return QR-ready compressed bytes (UTF-8 ASCII, `"9"` prefix + base10 digits)
    let generateCompressedVpTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateCompressedVpToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateCompressedVpTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rawSdJwtArg = args[0] as! String
        let paramsArg = args[1] as! VpTokenParams
        api.generateCompressedVpToken(rawSdJwt: rawSdJwtArg, params: paramsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateCompressedVpTokenChannel.setMessageHandler(nil)
    }
    /// Generate a test mDL VCDM2 SD-JWT credential, returned as a compact
    /// SD-JWS string.
    ///
    /// The credential mirrors the schema CA DMV will issue once the SD-JWT
    /// microservice ships, but is signed with a test key generated on demand —
    /// so the credential is **not** verifiable against any production trust
    /// anchor. Useful for showcase / demo flows that need a real SD-JWT to
    /// drive [generateCompressedVpToken] without depending on a live issuer.
    ///
    /// @return Compact SD-JWT serialization (`<jwt>~<disc1>~…`) — feed straight
    ///         to [generateCredentialVpToken] / [generateCompressedVpToken]
    ///         as `rawSdJwt`.
    let generateTestMdlSdJwtCompactChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateTestMdlSdJwtCompact\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateTestMdlSdJwtCompactChannel.setMessageHandler { _, reply in
        api.generateTestMdlSdJwtCompact { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateTestMdlSdJwtCompactChannel.setMessageHandler(nil)
    }
    /// Verify a compact SD-JWT VP token.
    ///
    /// Accepts either a raw compact SD-JWT (`<jwt>~<disc1>~…`) or a
    /// `"9"`-prefixed base10 QR payload — the implementation auto-detects the
    /// leading `"9"` and decompresses transparently before verifying. Throws
    /// on any failure (issuer signature mismatch, decompression error,
    /// disclosure hash mismatch, etc.); returns normally on success.
    ///
    /// Issuer trust is established via DID resolution (`AnyDidMethod`), so
    /// `did:jwk` issuers are fully verifiable offline.
    ///
    /// @param input Compact SD-JWT VP, or its `"9"`-prefixed compressed form
    ///              (e.g. straight from a [SpruceScanner] callback)
    let verifySdJwtVpChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.verifySdJwtVp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verifySdJwtVpChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputArg = args[0] as! String
        api.verifySdJwtVp(input: inputArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      verifySdJwtVpChannel.setMessageHandler(nil)
    }
    /// Decompress a `"9"`-prefixed base10 QR payload back into a compact
    /// SD-JWT VP token.
    ///
    /// The inverse of the compression step inside [generateCompressedVpToken].
    /// Verification code typically does **not** need to call this directly —
    /// `verifySdJwtVp` auto-detects the prefix and decompresses internally —
    /// but it is exposed for inspection, logging, or non-verification flows
    /// (e.g. extracting fields client-side from a scanned QR).
    ///
    /// @param qrPayload Bytes scanned from the QR (`"9"` prefix + base10 digits)
    /// @return Original compact SD-JWT VP token bytes (UTF-8)
    let decompressVpFromQrChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.decompressVpFromQr\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decompressVpFromQrChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let qrPayloadArg = args[0] as! FlutterStandardTypedData
        api.decompressVpFromQr(qrPayload: qrPayloadArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      decompressVpFromQrChannel.setMessageHandler(nil)
    }
  }
}
