// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class SpruceUtilsPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "SpruceUtilsPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? SpruceUtilsPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsSpruceUtils(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashSpruceUtils(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsSpruceUtils(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsSpruceUtils(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsSpruceUtils(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsSpruceUtils(lhsKey, rhsKey) {
          if deepEqualsSpruceUtils(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsSpruceUtils(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashSpruceUtils(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashSpruceUtils(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashSpruceUtils(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashSpruceUtils(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashSpruceUtils(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashSpruceUtils(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Result of generating a mock mDL
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol GenerateMockMdlResult {

}

/// Mock mDL generated successfully - stored in a CredentialPack
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerateMockMdlSuccess: GenerateMockMdlResult {
  /// The credential pack ID where the mDL was stored
  var packId: String
  /// The credential ID of the generated mDL
  var credentialId: String
  /// The raw mSO mDoc as base64 string for storage
  var rawCredential: String
  /// The key alias used for signing
  var keyAlias: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerateMockMdlSuccess? {
    let packId = pigeonVar_list[0] as! String
    let credentialId = pigeonVar_list[1] as! String
    let rawCredential = pigeonVar_list[2] as! String
    let keyAlias = pigeonVar_list[3] as! String

    return GenerateMockMdlSuccess(
      packId: packId,
      credentialId: credentialId,
      rawCredential: rawCredential,
      keyAlias: keyAlias
    )
  }
  func toList() -> [Any?] {
    return [
      packId,
      credentialId,
      rawCredential,
      keyAlias,
    ]
  }
  static func == (lhs: GenerateMockMdlSuccess, rhs: GenerateMockMdlSuccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.packId, rhs.packId) && deepEqualsSpruceUtils(lhs.credentialId, rhs.credentialId) && deepEqualsSpruceUtils(lhs.rawCredential, rhs.rawCredential) && deepEqualsSpruceUtils(lhs.keyAlias, rhs.keyAlias)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerateMockMdlSuccess")
    deepHashSpruceUtils(value: packId, hasher: &hasher)
    deepHashSpruceUtils(value: credentialId, hasher: &hasher)
    deepHashSpruceUtils(value: rawCredential, hasher: &hasher)
    deepHashSpruceUtils(value: keyAlias, hasher: &hasher)
  }
}

/// Mock mDL generation failed
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerateMockMdlError: GenerateMockMdlResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerateMockMdlError? {
    let message = pigeonVar_list[0] as! String

    return GenerateMockMdlError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: GenerateMockMdlError, rhs: GenerateMockMdlError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSpruceUtils(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerateMockMdlError")
    deepHashSpruceUtils(value: message, hasher: &hasher)
  }
}

private class SpruceUtilsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GenerateMockMdlSuccess.fromList(self.readValue() as! [Any?])
    case 130:
      return GenerateMockMdlError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SpruceUtilsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GenerateMockMdlSuccess {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? GenerateMockMdlError {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SpruceUtilsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SpruceUtilsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SpruceUtilsPigeonCodecWriter(data: data)
  }
}

class SpruceUtilsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SpruceUtilsPigeonCodec(readerWriter: SpruceUtilsPigeonCodecReaderWriter())
}


/// Utility functions for credential operations
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SpruceUtils {
  /// Generate a mock mDL for testing
  ///
  /// Creates a self-signed test mDL credential and stores it in a new
  /// CredentialPack. The returned packId and credentialId can be used with
  /// MdlPresentation.initializeQrPresentation().
  ///
  /// @param keyAlias Optional key alias to use (defaults to "testMdl")
  /// @return Result with packId, credentialId, rawCredential, and keyAlias, or error
  func generateMockMdl(keyAlias: String?, completion: @escaping (Result<GenerateMockMdlResult, Error>) -> Void)
  /// Generate a PDF from a raw mDL credential.
  ///
  /// Accepts the raw mSO mDoc as a base64url-encoded IssuerSigned string
  /// (the same format returned by generateMockMdl's rawCredential field).
  ///
  /// @param rawMdoc Base64url-encoded IssuerSigned bytes of the mDL
  /// @return Raw PDF bytes ready to write to a file and share
  func generateCredentialPdf(rawMdoc: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SpruceUtilsSetup {
  static var codec: FlutterStandardMessageCodec { SpruceUtilsPigeonCodec.shared }
  /// Sets up an instance of `SpruceUtils` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SpruceUtils?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generate a mock mDL for testing
    ///
    /// Creates a self-signed test mDL credential and stores it in a new
    /// CredentialPack. The returned packId and credentialId can be used with
    /// MdlPresentation.initializeQrPresentation().
    ///
    /// @param keyAlias Optional key alias to use (defaults to "testMdl")
    /// @return Result with packId, credentialId, rawCredential, and keyAlias, or error
    let generateMockMdlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateMockMdl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateMockMdlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg: String? = nilOrValue(args[0])
        api.generateMockMdl(keyAlias: keyAliasArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateMockMdlChannel.setMessageHandler(nil)
    }
    /// Generate a PDF from a raw mDL credential.
    ///
    /// Accepts the raw mSO mDoc as a base64url-encoded IssuerSigned string
    /// (the same format returned by generateMockMdl's rawCredential field).
    ///
    /// @param rawMdoc Base64url-encoded IssuerSigned bytes of the mDL
    /// @return Raw PDF bytes ready to write to a file and share
    let generateCredentialPdfChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.SpruceUtils.generateCredentialPdf\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateCredentialPdfChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rawMdocArg = args[0] as! String
        api.generateCredentialPdf(rawMdoc: rawMdocArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateCredentialPdfChannel.setMessageHandler(nil)
    }
  }
}
