// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class VcalmPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "VcalmPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? VcalmPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsVcalm(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashVcalm(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsVcalm(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsVcalm(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsVcalm(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsVcalm(lhsKey, rhsKey) {
          if deepEqualsVcalm(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsVcalm(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashVcalm(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashVcalm(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashVcalm(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashVcalm(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashVcalm(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashVcalm(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// The outcome of one VCALM (`vcapi`) exchange step.
///
/// Mirrors the Rust `StepResult` enum
/// (`Request | Offer | Redirect | Complete | Problem`), which is the stable
/// cross-layer surface. Pigeon and UniFFI are separate codegens that meet
/// inside the native adapter: the adapter projects the UniFFI `StepResult`
/// returned by `VcalmHolder` onto this sealed hierarchy.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol VcalmStepResult {

}

/// The verifier asked for a presentation (a Verifiable-Presentation-Request).
///
/// The VPR itself is projected to display data — `challenge`/`domain`/`purpose`
/// plus, via [Vcalm.requestedFields], the named fields. [vprListsSdSuite] is an
/// indicator the adapter computes from `Vpr.accepted_cryptosuites` so the demo
/// can show whether the selective-disclosure leg is in play. The cryptosuite
/// itself is server-driven — there is no client toggle.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmRequest: VcalmStepResult {
  var challenge: String? = nil
  var domain: String? = nil
  var purpose: String? = nil
  var vprListsSdSuite: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmRequest? {
    let challenge: String? = nilOrValue(pigeonVar_list[0])
    let domain: String? = nilOrValue(pigeonVar_list[1])
    let purpose: String? = nilOrValue(pigeonVar_list[2])
    let vprListsSdSuite = pigeonVar_list[3] as! Bool

    return VcalmRequest(
      challenge: challenge,
      domain: domain,
      purpose: purpose,
      vprListsSdSuite: vprListsSdSuite
    )
  }
  func toList() -> [Any?] {
    return [
      challenge,
      domain,
      purpose,
      vprListsSdSuite,
    ]
  }
  static func == (lhs: VcalmRequest, rhs: VcalmRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.challenge, rhs.challenge) && deepEqualsVcalm(lhs.domain, rhs.domain) && deepEqualsVcalm(lhs.purpose, rhs.purpose) && deepEqualsVcalm(lhs.vprListsSdSuite, rhs.vprListsSdSuite)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmRequest")
    deepHashVcalm(value: challenge, hasher: &hasher)
    deepHashVcalm(value: domain, hasher: &hasher)
    deepHashVcalm(value: purpose, hasher: &hasher)
    deepHashVcalm(value: vprListsSdSuite, hasher: &hasher)
  }
}

/// The issuer offered one or more credentials.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmOffer: VcalmStepResult {
  var credentials: [VcalmOfferedCredentialData]
  var hasNextRequest: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmOffer? {
    let credentials = pigeonVar_list[0] as! [VcalmOfferedCredentialData]
    let hasNextRequest = pigeonVar_list[1] as! Bool

    return VcalmOffer(
      credentials: credentials,
      hasNextRequest: hasNextRequest
    )
  }
  func toList() -> [Any?] {
    return [
      credentials,
      hasNextRequest,
    ]
  }
  static func == (lhs: VcalmOffer, rhs: VcalmOffer) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.credentials, rhs.credentials) && deepEqualsVcalm(lhs.hasNextRequest, rhs.hasNextRequest)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmOffer")
    deepHashVcalm(value: credentials, hasher: &hasher)
    deepHashVcalm(value: hasNextRequest, hasher: &hasher)
  }
}

/// The exchange wants the holder to follow a redirect URL.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmRedirect: VcalmStepResult {
  var url: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmRedirect? {
    let url = pigeonVar_list[0] as! String

    return VcalmRedirect(
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      url
    ]
  }
  static func == (lhs: VcalmRedirect, rhs: VcalmRedirect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.url, rhs.url)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmRedirect")
    deepHashVcalm(value: url, hasher: &hasher)
  }
}

/// The exchange completed with nothing further to do.
///
/// The Rust `StepResult::Complete` is a unit variant carrying no data. Pigeon
/// (26.x) cannot codec a field-less data class in a sealed hierarchy, so this
/// member carries a single always-`true` marker. Match on the type, not the
/// flag.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmComplete: VcalmStepResult {
  var completed: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmComplete? {
    let completed = pigeonVar_list[0] as! Bool

    return VcalmComplete(
      completed: completed
    )
  }
  func toList() -> [Any?] {
    return [
      completed
    ]
  }
  static func == (lhs: VcalmComplete, rhs: VcalmComplete) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.completed, rhs.completed)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmComplete")
    deepHashVcalm(value: completed, hasher: &hasher)
  }
}

/// The exchange returned an RFC 9457 problem document.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmProblem: VcalmStepResult {
  var problemType: String
  var status: Int64? = nil
  var title: String? = nil
  var detail: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmProblem? {
    let problemType = pigeonVar_list[0] as! String
    let status: Int64? = nilOrValue(pigeonVar_list[1])
    let title: String? = nilOrValue(pigeonVar_list[2])
    let detail: String? = nilOrValue(pigeonVar_list[3])

    return VcalmProblem(
      problemType: problemType,
      status: status,
      title: title,
      detail: detail
    )
  }
  func toList() -> [Any?] {
    return [
      problemType,
      status,
      title,
      detail,
    ]
  }
  static func == (lhs: VcalmProblem, rhs: VcalmProblem) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.problemType, rhs.problemType) && deepEqualsVcalm(lhs.status, rhs.status) && deepEqualsVcalm(lhs.title, rhs.title) && deepEqualsVcalm(lhs.detail, rhs.detail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmProblem")
    deepHashVcalm(value: problemType, hasher: &hasher)
    deepHashVcalm(value: status, hasher: &hasher)
    deepHashVcalm(value: title, hasher: &hasher)
    deepHashVcalm(value: detail, hasher: &hasher)
  }
}

/// Result of creating a holder session.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol VcalmResult {

}

/// Holder session created successfully.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmSuccess: VcalmResult {
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmSuccess? {
    let message: String? = nilOrValue(pigeonVar_list[0])

    return VcalmSuccess(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: VcalmSuccess, rhs: VcalmSuccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmSuccess")
    deepHashVcalm(value: message, hasher: &hasher)
  }
}

/// Holder session creation failed.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmError: VcalmResult {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmError? {
    let message = pigeonVar_list[0] as! String

    return VcalmError(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: VcalmError, rhs: VcalmError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmError")
    deepHashVcalm(value: message, hasher: &hasher)
  }
}

/// A field named by the current VPR's QueryByExample query.
///
/// Informational only: `ecdsa-rdfc-2019` reveals the entire credential, so this
/// surfaces what will be shared for user display — it does NOT limit fields.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmRequestedFieldData: Hashable {
  var queryIndex: Int64
  var path: String
  var value: String
  var required: Bool
  var purpose: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmRequestedFieldData? {
    let queryIndex = pigeonVar_list[0] as! Int64
    let path = pigeonVar_list[1] as! String
    let value = pigeonVar_list[2] as! String
    let required = pigeonVar_list[3] as! Bool
    let purpose: String? = nilOrValue(pigeonVar_list[4])

    return VcalmRequestedFieldData(
      queryIndex: queryIndex,
      path: path,
      value: value,
      required: required,
      purpose: purpose
    )
  }
  func toList() -> [Any?] {
    return [
      queryIndex,
      path,
      value,
      required,
      purpose,
    ]
  }
  static func == (lhs: VcalmRequestedFieldData, rhs: VcalmRequestedFieldData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.queryIndex, rhs.queryIndex) && deepEqualsVcalm(lhs.path, rhs.path) && deepEqualsVcalm(lhs.value, rhs.value) && deepEqualsVcalm(lhs.required, rhs.required) && deepEqualsVcalm(lhs.purpose, rhs.purpose)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmRequestedFieldData")
    deepHashVcalm(value: queryIndex, hasher: &hasher)
    deepHashVcalm(value: path, hasher: &hasher)
    deepHashVcalm(value: value, hasher: &hasher)
    deepHashVcalm(value: required, hasher: &hasher)
    deepHashVcalm(value: purpose, hasher: &hasher)
  }
}

/// A credential previewed from the current Offer.
///
/// [validity] is one of `valid` | `timeBounded` | `proofInvalid` | `enveloped` |
/// `unverifiable`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmOfferedCredentialData: Hashable {
  var issuer: String? = nil
  var types: [String]
  var credentialSubject: String? = nil
  var validity: String
  /// The full offered VC as a JSON string. `acceptOffer` stores the credential
  /// only in the holder's own VdcCollection; the host app uses this raw VC to
  /// persist it into its OWN wallet store so a VCALM-received credential appears
  /// in the app's credential list.
  var rawCredential: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmOfferedCredentialData? {
    let issuer: String? = nilOrValue(pigeonVar_list[0])
    let types = pigeonVar_list[1] as! [String]
    let credentialSubject: String? = nilOrValue(pigeonVar_list[2])
    let validity = pigeonVar_list[3] as! String
    let rawCredential = pigeonVar_list[4] as! String

    return VcalmOfferedCredentialData(
      issuer: issuer,
      types: types,
      credentialSubject: credentialSubject,
      validity: validity,
      rawCredential: rawCredential
    )
  }
  func toList() -> [Any?] {
    return [
      issuer,
      types,
      credentialSubject,
      validity,
      rawCredential,
    ]
  }
  static func == (lhs: VcalmOfferedCredentialData, rhs: VcalmOfferedCredentialData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.issuer, rhs.issuer) && deepEqualsVcalm(lhs.types, rhs.types) && deepEqualsVcalm(lhs.credentialSubject, rhs.credentialSubject) && deepEqualsVcalm(lhs.validity, rhs.validity) && deepEqualsVcalm(lhs.rawCredential, rhs.rawCredential)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmOfferedCredentialData")
    deepHashVcalm(value: issuer, hasher: &hasher)
    deepHashVcalm(value: types, hasher: &hasher)
    deepHashVcalm(value: credentialSubject, hasher: &hasher)
    deepHashVcalm(value: validity, hasher: &hasher)
    deepHashVcalm(value: rawCredential, hasher: &hasher)
  }
}

/// Stable key for a credential matched within a single VCALM session.
///
/// The Rust `ParsedCredential` is an opaque UniFFI `Object` handle that CANNOT
/// cross Pigeon. The native adapter retains the live handles in a key-map and
/// accepts these lightweight keys back from Dart. A credential is identified by
/// the pair `(queryIndex, credentialId)`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VcalmCredentialKey: Hashable {
  var queryIndex: Int64
  var credentialId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VcalmCredentialKey? {
    let queryIndex = pigeonVar_list[0] as! Int64
    let credentialId = pigeonVar_list[1] as! String

    return VcalmCredentialKey(
      queryIndex: queryIndex,
      credentialId: credentialId
    )
  }
  func toList() -> [Any?] {
    return [
      queryIndex,
      credentialId,
    ]
  }
  static func == (lhs: VcalmCredentialKey, rhs: VcalmCredentialKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVcalm(lhs.queryIndex, rhs.queryIndex) && deepEqualsVcalm(lhs.credentialId, rhs.credentialId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VcalmCredentialKey")
    deepHashVcalm(value: queryIndex, hasher: &hasher)
    deepHashVcalm(value: credentialId, hasher: &hasher)
  }
}

private class VcalmPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VcalmRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return VcalmOffer.fromList(self.readValue() as! [Any?])
    case 131:
      return VcalmRedirect.fromList(self.readValue() as! [Any?])
    case 132:
      return VcalmComplete.fromList(self.readValue() as! [Any?])
    case 133:
      return VcalmProblem.fromList(self.readValue() as! [Any?])
    case 134:
      return VcalmSuccess.fromList(self.readValue() as! [Any?])
    case 135:
      return VcalmError.fromList(self.readValue() as! [Any?])
    case 136:
      return VcalmRequestedFieldData.fromList(self.readValue() as! [Any?])
    case 137:
      return VcalmOfferedCredentialData.fromList(self.readValue() as! [Any?])
    case 138:
      return VcalmCredentialKey.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VcalmPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VcalmRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmOffer {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmRedirect {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmComplete {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmProblem {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmSuccess {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmError {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmRequestedFieldData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmOfferedCredentialData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? VcalmCredentialKey {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VcalmPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VcalmPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VcalmPigeonCodecWriter(data: data)
  }
}

class VcalmPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VcalmPigeonCodec(readerWriter: VcalmPigeonCodecReaderWriter())
}


/// VCALM (`vcapi`) holder presentation + issuance API.
///
/// Drives one `vcapi` exchange end-to-end: receive a credential via VCALM
/// issuance (Offer → accept), then present it via QueryByExample (Request →
/// submit). All protocol logic lives in the Rust `VcalmHolder`; this surface is
/// a pure marshaling contract.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Vcalm {
  /// Build the holder session.
  ///
  /// The signer is `did:key` over the named keystore key (the one deliberate
  /// divergence from OID4VP, which uses `did:jwk`).
  ///
  /// @param credentialPackIds Credential pack IDs to enumerate for QBE matching
  /// @param trustedDids Trusted DIDs for verification (forward-looking)
  /// @param keyId The keystore key identifier for signing (created if absent)
  /// @param contextMap Optional JSON-LD context map
  func createHolder(credentialPackIds: [String], trustedDids: [String], keyId: String, contextMap: [String: String]?, completion: @escaping (Result<VcalmResult, Error>) -> Void)
  /// Start the exchange from an `interaction:`/`https` URL.
  ///
  /// @param url The exchange or discovery URL
  /// @param authHeader Optional bearer token sent on exchange POSTs (never on
  ///   the discovery GET)
  /// @return The first [VcalmStepResult]
  func startExchange(url: String, authHeader: String?, completion: @escaping (Result<VcalmStepResult, Error>) -> Void)
  /// Matched credentials for the current VPR's QueryByExample queries.
  ///
  /// @return Stable keys only (the opaque handles stay native)
  func matchedCredentials(completion: @escaping (Result<[VcalmCredentialKey], Error>) -> Void)
  /// Fields named by the current VPR (for user display).
  func requestedFields(completion: @escaping (Result<[VcalmRequestedFieldData], Error>) -> Void)
  /// Submit a Verifiable Presentation for the selected credentials.
  ///
  /// The chosen cryptosuite is server-driven.
  ///
  /// @param selected Stable keys of the credentials the user selected
  /// @param allowDomainMismatch Proceed even if the VPR `domain` does not match
  ///   the exchange channel host (§3.4.3.2 anti-replay). Set only after explicit
  ///   user consent — never as a default. A domain mismatch otherwise returns a
  ///   [VcalmProblem] with `problemType == "domain-mismatch"`.
  func submitPresentation(selected: [VcalmCredentialKey], allowDomainMismatch: Bool, completion: @escaping (Result<VcalmStepResult, Error>) -> Void)
  /// Preview the credentials offered in the current Offer.
  func offeredCredentials(completion: @escaping (Result<[VcalmOfferedCredentialData], Error>) -> Void)
  /// Accept the current Offer (verify + store), then advance the exchange.
  func acceptOffer(completion: @escaping (Result<VcalmStepResult, Error>) -> Void)
  /// Reject the current Offer, then advance the exchange.
  func rejectOffer(completion: @escaping (Result<VcalmStepResult, Error>) -> Void)
  /// Cancel and clean up the current session.
  func cancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VcalmSetup {
  static var codec: FlutterStandardMessageCodec { VcalmPigeonCodec.shared }
  /// Sets up an instance of `Vcalm` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Vcalm?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Build the holder session.
    ///
    /// The signer is `did:key` over the named keystore key (the one deliberate
    /// divergence from OID4VP, which uses `did:jwk`).
    ///
    /// @param credentialPackIds Credential pack IDs to enumerate for QBE matching
    /// @param trustedDids Trusted DIDs for verification (forward-looking)
    /// @param keyId The keystore key identifier for signing (created if absent)
    /// @param contextMap Optional JSON-LD context map
    let createHolderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.createHolder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createHolderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialPackIdsArg = args[0] as! [String]
        let trustedDidsArg = args[1] as! [String]
        let keyIdArg = args[2] as! String
        let contextMapArg: [String: String]? = nilOrValue(args[3])
        api.createHolder(credentialPackIds: credentialPackIdsArg, trustedDids: trustedDidsArg, keyId: keyIdArg, contextMap: contextMapArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createHolderChannel.setMessageHandler(nil)
    }
    /// Start the exchange from an `interaction:`/`https` URL.
    ///
    /// @param url The exchange or discovery URL
    /// @param authHeader Optional bearer token sent on exchange POSTs (never on
    ///   the discovery GET)
    /// @return The first [VcalmStepResult]
    let startExchangeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.startExchange\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startExchangeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let authHeaderArg: String? = nilOrValue(args[1])
        api.startExchange(url: urlArg, authHeader: authHeaderArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startExchangeChannel.setMessageHandler(nil)
    }
    /// Matched credentials for the current VPR's QueryByExample queries.
    ///
    /// @return Stable keys only (the opaque handles stay native)
    let matchedCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.matchedCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      matchedCredentialsChannel.setMessageHandler { _, reply in
        api.matchedCredentials { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      matchedCredentialsChannel.setMessageHandler(nil)
    }
    /// Fields named by the current VPR (for user display).
    let requestedFieldsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.requestedFields\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestedFieldsChannel.setMessageHandler { _, reply in
        api.requestedFields { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestedFieldsChannel.setMessageHandler(nil)
    }
    /// Submit a Verifiable Presentation for the selected credentials.
    ///
    /// The chosen cryptosuite is server-driven.
    ///
    /// @param selected Stable keys of the credentials the user selected
    /// @param allowDomainMismatch Proceed even if the VPR `domain` does not match
    ///   the exchange channel host (§3.4.3.2 anti-replay). Set only after explicit
    ///   user consent — never as a default. A domain mismatch otherwise returns a
    ///   [VcalmProblem] with `problemType == "domain-mismatch"`.
    let submitPresentationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.submitPresentation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitPresentationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let selectedArg = args[0] as! [VcalmCredentialKey]
        let allowDomainMismatchArg = args[1] as! Bool
        api.submitPresentation(selected: selectedArg, allowDomainMismatch: allowDomainMismatchArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitPresentationChannel.setMessageHandler(nil)
    }
    /// Preview the credentials offered in the current Offer.
    let offeredCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.offeredCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      offeredCredentialsChannel.setMessageHandler { _, reply in
        api.offeredCredentials { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      offeredCredentialsChannel.setMessageHandler(nil)
    }
    /// Accept the current Offer (verify + store), then advance the exchange.
    let acceptOfferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.acceptOffer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acceptOfferChannel.setMessageHandler { _, reply in
        api.acceptOffer { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      acceptOfferChannel.setMessageHandler(nil)
    }
    /// Reject the current Offer, then advance the exchange.
    let rejectOfferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.rejectOffer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rejectOfferChannel.setMessageHandler { _, reply in
        api.rejectOffer { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      rejectOfferChannel.setMessageHandler(nil)
    }
    /// Cancel and clean up the current session.
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sprucekit_mobile.Vcalm.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
