name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - run: brew install swiftlint

    - name: Test
      uses: mxcl/xcodebuild@v2
      with:
        platform: iOS

    - name: Lint
      run: swiftlint lint --strict
