name: ReferenceApp
options:
  bundleIdPrefix: com.spruceid.mobile
packages:
  SpruceIDMobileSdk:
    # url: https://github.com/spruceid/sprucekit-mobile
    # from: 0.3.0
    # revision: "9376148"
    path: "../../"
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift.git
    revision: a95fc6df17d108bd99210db5e8a9bac90fe984b8
    version: 0.15.3
  RiveRuntime:
    url: https://github.com/rive-app/rive-ios
    revision: fa6c4ee
    version: 6.1.6
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  ENABLE_MODULE_VERIFIER: YES
  DEVELOPMENT_TEAM: FZVYR3KYL4
  # "CODE_SIGN_IDENTITY": "Spruce Systems, Inc. (FZVYR3KYL4)"
targets:
  App:
    type: application
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: "Targets/App/Sources"
        createIntermediateGroups: true
      - path: "Resources"
        createIntermediateGroups: true
      - path: Targets/AppUIKit/Sources/jsonLdContexts
        createIntermediateGroups: true
    dependencies:
      - target: AppAppKit
      - target: AppUIKit
      # - target: AppDcApi
      - package: RiveRuntime
    scheme:
      testTargets:
        - AppAppKitTests
        - AppUIKitTests
    info:
      path: Info.plist
      properties:
        CFBundleVersion: "1.15.1"
        CFBundleShortVersionString: "1.15.1"
        CFBundleDisplayName: "SpruceKit"
        CFBundleIconName: "AppIcon"
        CFBundlePackageType: "APPL"
        CFBundleURLTypes:
          - CFBundleTypeRole: Viewer
            CFBundleURLName: OID4VP
            CFBundleURLSchemes:
              - openid4vp
          - CFBundleTypeRole: Viewer
            CFBundleURLName: SPRUCEID
            CFBundleURLSchemes:
              - spruceid
          - CFBundleTypeRole: Viewer
            CFBundleURLName: OID4VCI
            CFBundleURLSchemes:
              - openid-credential-offer
          - CFBundleTypeRole: Viewer
            CFBundleURLName: MdocOID4VP
            CFBundleURLSchemes:
              - mdoc-openid4vp
        NSBluetoothAlwaysUsageDescription: "Secure transmission of mobile DL data"
        NSCameraUsageDescription: "We need to access your camera for scanning"
        ITSAppUsesNonExemptEncryption: "NO"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
          - telephony
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        UIUserInterfaceStyle: "Light"
        UIAppFonts:
          - Inter-Black.ttf
          - Inter-BlackItalic.ttf
          - Inter-Bold.ttf
          - Inter-BoldItalic.ttf
          - Inter-ExtraBold.ttf
          - Inter-ExtraBoldItalic.ttf
          - Inter-ExtraLight.ttf
          - Inter-ExtraLightItalic.ttf
          - Inter-Italic.ttf
          - Inter-Light.ttf
          - Inter-LightItalic.ttf
          - Inter-Medium.ttf
          - Inter-MediumItalic.ttf
          - Inter-Regular.ttf
          - Inter-Semibold.ttf
          - Inter-SemiboldItalic.ttf
          - Inter-Thin.ttf
          - Inter-ThinItalic.ttf
        storageAppGroup: group.com.spruceid.mobile # custom property to know what the app group is, because the app cannot access entitlements
        keychainAccessGroupAppOnly: "$(AppIdentifierPrefix)com.spruceid.mobile" # custom property to know what the access group is, because the app cannot access entitlements
        keychainAccessGroup: "$(AppIdentifierPrefix)keychain.com.spruceid.mobile" # custom property to know what the access group is, because the app cannot access entitlements
    entitlements:
      path: App.entitlements
      properties:
        # to be able to share the filesystem with the dc api extension
        com.apple.security.application-groups:
          - group.com.spruceid.mobile
        # com.apple.developer.identity-document-services.document-provider.mobile-document-types:
        #   - "org.iso.18013.5.1.mDL"
        # to be able to share the keychain with the dc api extension
        keychain-access-groups:
          - "$(AppIdentifierPrefix)keychain.com.spruceid.mobile"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
  AppAppKit:
    type: framework
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: "Targets/AppAppKit/Sources"
        createIntermediateGroups: true
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.kit
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
  AppAppKitTests:
    type: bundle.unit-test
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: "Targets/AppAppKit/Tests"
        createIntermediateGroups: true
    dependencies:
      - target: AppAppKit
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.kittests
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
  AppUIKit:
    type: framework
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: "Targets/AppUIKit/Sources"
        createIntermediateGroups: true
    dependencies:
      - package: SpruceIDMobileSdk
        product: SpruceIDMobileSdk
      - package: SQLite
      - package: RiveRuntime
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.ui
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
  AppUIKitTests:
    type: bundle.unit-test
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: "Targets/AppUIKit/Tests"
        createIntermediateGroups: true
    dependencies:
      - target: AppUIKit
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.uitests
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
  AppDcApi:
    type: extensionkit-extension
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: "Targets/AppDcApi/Sources"
        createIntermediateGroups: true
      - path: "Resources"
        createIntermediateGroups: true
    dependencies:
      # `embed` defaults to true only for application type
      - target: AppAppKit
        embed: true
      - target: AppUIKit
        embed: true
      - package: RiveRuntime # for AppUIKit
    info:
      path: Targets/AppDcApi/Info.plist
      properties:
        CFBundleDisplayName: "Showcase DC API Extension"
        EXAppExtensionAttributes:
          EXExtensionPointIdentifier: com.apple.identity-document-services.document-provider-ui
        storageAppGroup: group.com.spruceid.mobile # custom property to know what the app group is, because the app cannot access entitlements
    entitlements:
      path: Targets/AppDcApi/App.entitlements
      properties:
        # to be able to share the filesystem with the host app
        com.apple.security.application-groups:
          - group.com.spruceid.mobile
        # to be able to share the keychain with the host app
        keychain-access-groups:
          - "$(AppIdentifierPrefix)keychain.com.spruceid.mobile"
    settings:
      base:
        INFOPLIST_FILE: Targets/AppDcApi/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.spruceid.mobile.dcapi
        INFOPLIST_KEY_CFBundleDisplayName: Showcase DC API Extension
        TARGETED_DEVICE_FAMILY: 1
        # don't know why the riveruntime frameworks isn't being placed under this extension's directory, so we have to look in the host app's
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
configs:
  debug: debug
  release: release
schemes:
  release:
    shared: true
    build:
      targets:
        App: [build, archive]
        # AppDcApi: [build, archive]
    run:
      targets:
        App: [run]
        # AppDcApi: [run]
    test:
      targets:
        - App
        - AppAppKitTests
        - AppUIKitTests
        # - AppDcApi
    archive:
      config: release
  debug:
    shared: true
    build:
      targets:
        App: [build, archive]
        # AppDcApi: [build, archive]
    run:
      targets:
        App: [run]
        # AppDcApi: [run]
    test:
      targets:
        - App
        - AppAppKitTests
        - AppUIKitTests
        # - AppDcApi
    archive:
      config: debug
