name: mobile-sdk-kt CI

on:
  push:
    branches: [main]
    paths:
      - "mobile-sdk-kt/**"
  pull_request:
    branches: [main]
    paths:
      - "mobile-sdk-kt/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintDebug
          build-root-directory: ./mobile-sdk-kt

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: ./mobile-sdk-kt
