name: mobile-sdk-swift push

on:
  push:
    branches: [main]
    paths:
      - "mobile-sdk-swift/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MONOREPO_GITHUB_ACCESS_TOKEN }}
      - name: Push subtree
        run: |
          git subtree push --prefix=mobile-sdk-swift/ https://github.com/spruceid/mobile-sdk-swift.git main
